### ISSUE TITLE
[New Exchange Connector] Why are we wasting time?

### ISSUE THREAD

**Issue by joesixpack** [CoinAlpha/hummingbot#1088]
We really don't need to be wasting our collective time waiting for and/or building individual exchange connectors for mostly shitchanges.  There already is a long established library supporting 120+ exchanges to tap into!!!

https://github.com/ccxt/ccxt

Request that Hummingbot team make Hummingbot compatible with it.

**Comment by yzhang1994** [comment]
@joesixpack Please use respectful language when raising issues and commenting.

**Comment by yzhang1994** [comment]
There are a couple of reasons why we haven't integrated with ccxt. A few main ones:
- ccxt only abstracts away the API layer but doesn't account for the idiosyncrasies on each exchange, such as Binance server time sync.
- hummingbot manages a real-time order book and has built-in order tracking, which is difficult to accomplish with ccxt, since each exchange API returns unique errors that need to be handled differently. 

Reliability is critical for a high-frequency trading system. Otherwise, people who run the bot WILL lose money. We are doing our best to extend our codebase without sacrificing quality.

There may be a way in the future for the two projects to collaborate in the future. But it isn't currently in our roadmap.
