### ISSUE TITLE
[BUG] Wallet import broken 

### ISSUE THREAD

**Issue by 7--** [CoinAlpha/hummingbot#1329]
![Screenshot from 2020-01-18 18-30-05](https://user-images.githubusercontent.com/4725003/72671965-a9c75980-3a20-11ea-8b12-f1ca9d2557cf.png)

**Comment by 7--** [comment]
As you see there's no way to import a eth wallet from metamask.

**Comment by 7--** [comment]
Also the  highlighing and copying is broken. Even when holding the "fn" key

**Comment by 7--** [comment]
Also there's no way to go back to the last prompt or quite without completly breaking down everyhing

**Comment by 7--** [comment]
Also the scrollbar doesnt work

**Comment by 7--** [comment]
Also whenever you enter config it asks every single qusiot again

**Comment by 7--** [comment]
Also no way to answer this: 
![Screenshot from 2020-01-18 19-17-42](https://user-images.githubusercontent.com/4725003/72672399-4a207c80-3a27-11ea-8999-8407ba40e958.png)

**Comment by MishaelTereso** [comment]
@7-- There are two ways to import your Hummingbot wallet from other wallets like Metamask and MyCrypto:

1. Importing the wallet's keyfile (recommended)
2. Importing the wallet's private key

You can check the steps and instruction here https://docs.hummingbot.io/installation/wallet/#private-key_1 and please take a look with some script there, it would definitely help you to configure it properly. 

Also, You need an Ethereum node for strategies that trade on Ethereum-based decentralized exchanges. To set up an Ethereum node please check this doc https://docs.hummingbot.io/installation/node/node/

If bot is asking question, that means that parameter should be answered and cannot be blank or incorrect. The bot needs those information in order to make it work.

**Comment by PtrckM** [comment]
@7-- we have documentations as well for ethereum nodes, please visit https://docs.hummingbot.io/installation/node/node/

**Comment by yzhang1994** [comment]
@MishaelTereso Have you tried to reproduce this issue and verify it's valid?

**Comment by MishaelTereso** [comment]
@yzhang1994 I replicated the issue and was not able to reproduce the issue. This is not present to master or development branch. Not a BUG after all.

**Comment by yzhang1994** [comment]
@MishaelTereso Thanks
