### ISSUE TITLE
mid point is moving 

### ISSUE THREAD

**Issue by walterkok** [CoinAlpha/hummingbot#1341]
i noticed when I launch a tradingbot wiht a 40% distance from the midpoint on buy and a 25% distance from the midpoint on sell, the opening is correct but then each time a new bid sell is refreshed the  bids / sells of the bot is trending down (no buy or sell happening).
if you do the same % (e.g.40%) on both sides it operates correctly
The bot is trading on liquid and my analysis is that the midpoint is not being calculated on the bids that are in the orderbook already but on the orderbook including the orders of the bot. This is not what should be happening in my view

**Comment by Clint-G13** [comment]
Hi, I was testing your threshold parameter using paper trade mode and set cancel_order_wait_time = 10 seconds so that orders get refreshed immediately. Unfortunately, I was not able to reproduce that behavior. My bot is still placing buy and sell order and recomputes the mid-price whenever order gets refreshed. For me to check further, can you send me your logs, strategy file, and a screenshot of your bot showing that behavior. You can also, post this concern through our support channel:  https://discord.hummingbot.io/
