### ISSUE TITLE
Hummingbot installation for Windows is hard to find

### ISSUE THREAD

**Issue by martinkou** [CoinAlpha/hummingbot#141]
This is Ellie.

I find the windows installation instructions for Hummingbot to be hard to find. I am using a very low resolution screen so it's not clear where to click. Please triage.

![b1-screen](https://user-images.githubusercontent.com/304402/56858986-fa4dd280-6938-11e9-8d30-8114d4a4b6d5.png)

Repro steps:
1. Go to https://www.hummingbot.io/
2. Click "Installation Guide"
3. Look for the text "Windows 10 or later (see Windows section below)"

Expected:
- Clickable link to a dedicated page for installing Hummingbot on Windows
- OR below where there is a clear link to Windows section

Actual:
- Link is not clickable and is hidden in the upper left hamburger menu

**Comment by nsshommo** [comment]
@martinkou Thank you for opening this issue here and letting us know your valuable opinion. The team is working hard to update everything and make things more user-friendly. By this time if you need any help, you can join the community here: [https://discord.hummingbot.io]. In this community, you can find help very easily and quickly. Thanks again for your patience and co-operation.
