### ISSUE TITLE
Failed to install Hummingbot by following installation instructions for Windows

### ISSUE THREAD

**Issue by martinkou** [CoinAlpha/hummingbot#142]
This is Ellie.

I am trying to follow the installation instructions for Hummingbot on Windows. So far I have not been successful in installation so I'll describe what happened. Instructions are taken from here: https://docs.hummingbot.io/installation/docker/ .

I use cmd.exe, but installing I use the bash on Windows, which is not clear to me I'll need to install docker from Docker as an exe, and then the bash system still doesn't able to use Docker, so I realized I have to use cmd.exe.

The command provided on the installation guide is not platform agnostic too:

```
docker run -it \
--name $NAME \
-v "$PWD"/conf/:/conf/ \
-v "$PWD"/logs/:/logs/ \
coinalpha/hummingbot:$TAG
```

I ran the following variations:

First, using PWD doesn't work:

```
C:\Users\marti>docker run --init --name EllieBot2 -v "$PWD"/conf/:/conf/ -v "$PWD"/logs/:/logs/ coinalpha/hummingbot:latest
docker: Error response from daemon: create $PWD/conf: "$PWD/conf" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```

Then, using an absolute path (most natural guess), complains a 'conf' thing.

```
C:\Users\marti>docker run -i --name EllieBot3 -v C:\Users\Marti\EllieBot\conf\ -v C:\Users\Marti\EllieBot\logs coinalpha/hummingbot:latest
Traceback (most recent call last):
  File "/opt/conda/envs/hummingbot-dist/bin/hummingbot.py", line 28, in <module>
    from hummingbot.cli.hummingbot_application import HummingbotApplication
  File "/opt/conda/envs/hummingbot-dist/lib/python3.6/site-packages/hummingbot/cli/hummingbot_application.py", line 20, in <module>
    from wings.market.binance_market import BinanceMarket
  File "wings/market/binance_market.pyx", line 27, in init wings.market.binance_market
ModuleNotFoundError: No module named 'conf'
```

Also, "-it" does not work on Windows:

```
C:\Users\marti>docker run -i --name EllieBot2 -v "$PWD"/conf/:/conf/ -v "$PWD"/logs/:/logs/ coinalpha/hummingbot:latest
docker: Error response from daemon: create $PWD/conf: "$PWD/conf" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```

This is my specs:
- Windows 10
- Docker latest (installed from exe)

Expected:
- I will be able to install Hummingbot to try.

Actual:
- Unable to install Hummingbot on Windows to try.

**Comment by Steve1943** [comment]
Response depends if running [Home Edition] or [Pro | Enterprise] because Home Edition does not support Windows VM which is expected by the Windows version of Docker.  

There is a workaround using DockerToolkit - which attempts to substitute VirtualBox for Windows VM.
However, DockerToolkit is deprecated and tricky to use successfully.

I found it easier to either compile from source in Windows WSL - or create your own VirtualBox Ubuntu and install Hummingbot directly in that (with or without Linux Docker).  I have successfully done all three of these options without problem.

once Hummingbot is compiled from source, running several bots is as easy as opening an additional terminal instance to import a different strategy file - so Docker doesn't add much in my book.

**Comment by mifeng** [comment]
@nkona is working on a more comprehensive Windows installation guide that should be released soon.

**Comment by nkona** [comment]
Guides have been updated this week on the documentation, should be much easier to use!
