### ISSUE TITLE
[Feature] Allow limiting the amount of assets HB can access in an exchange/wallet

### ISSUE THREAD

**Issue by CryptoBeliever1** [CoinAlpha/hummingbot#1443]
**Feature Suggestion**
There should be an ability to limit the amount of assets HB can access/use in an exchange or wallet. The asset symbol and the limit size in asset units should be configurable.

**Impact**
It can be a good security measure to avoid unexpected and undesirable losses. Along with that, it is just convenient for a user who doesn't wish to remove the 'untouchable' amounts from the exchange/wallet before starting HB.

**Additional context**
None

**Comment by PtrckM** [comment]
The closes function that I could think of is Hummingbot feature called [kill-switch](https://docs.hummingbot.io/utilities/kill-switch/). Automatically stops the bot when it reaches a certain performance threshold, which can be either positive or negative.

But this could be a good new feature.

**Comment by mhardock** [comment]
I like this feature. Should be useful for users running bots on many different trading pairs with shared assets.

**Comment by Nullably** [comment]
After discussion with @dennisocana and @CrimsonJacket The way to think of this feature is actually budget allocation, not limit. Once the budget limit is set the bot needs to account for the followings:
- Outstanding maker orders, the balance used for these orders (including hanging orders) need to deduct from the budget.
- Filled orders, the bot needs to account for balances gain/reduce from orders being filled (similar to how exchange manages this, but we have to do it manually here as multiple can share the same trading account)

For example: 
If balances are

ETH  1 (available), 0.5 (limit)
LINK 4 (available), 1 (limit)

Assuming the price for LINK is 0.5 ETH

Once the bot has placed a maker buy order 1 LINK and a maker sell order 1 LINK, the budgets for both ETH and LINK are now 0. If the buy order is filled, ETH budget remains at 0 while LINK budget is now 2 (this is so that the bot can get back to it budget targets). The bot can no longer place a buy order until the sell order is filled. If later on a sell order is filled, ETH budget is now 0.5 and LINK budget is 1.

**Comment by Nullably** [comment]
As above, I'd like to propose changing the command and display to `budget` instead of `limit` to better convey what this feature is about.
