### ISSUE TITLE
[Question] minimum profitability and order prices irreconcilable

### ISSUE THREAD

**Issue by carlolm** [CoinAlpha/hummingbot#146]
Need an explanation of how order prices are calculated based on available taker prices/order book and minimum profitability.

For example, for XEMM, bid side (make bid order on ddex, take bid order on Binance).
Would assume that the bid price is the cost of hedging x (1 - min_profitability).

```
expected ddex_bid_price = binance_cost_of_purchase * (1 - min_profitability)

binance_cost_of_purchase = ∑ (binance_bid_price_i x binance_bid_size_i)
where i = 1 to n, such that ∑ binance_bid_size_i = trade_size
```

1. What happens if your pricing is the best bid/ask?  (seems like the prices are widened to try to capture additional profit), i.e. min_profit_bid_price > actual_bid_price > 
2. What happens if your pricing is not the best bid/ask?  (assume it just uses the min_profitability_price).

**Screenshots**
<img width="784" alt="Image 2019-04-28 at 10 37 10 pm" src="https://user-images.githubusercontent.com/12274903/56869880-b51eb480-69bb-11e9-84cd-f7308f0b5249.png">
<img width="298" alt="Image 2019-04-28 at 10 36 58 pm" src="https://user-images.githubusercontent.com/12274903/56869881-b51eb480-69bb-11e9-98fc-64863d545461.png">
<img width="614" alt="0a67e9803b6bcf0ab03dca04fc8ca206 _Image 2019-04-28 at 10 36 50 pm" src="https://user-images.githubusercontent.com/12274903/56869882-b5b74b00-69bb-11e9-8044-89b2a5224a0e.png">

**Release version**
0.4.0 as of April 28, 2019

**Comment by martinkou** [comment]
The order prices are widened up to the top depth tolerance setting in terms of quote tokens in the order book.

Say for example, I'm market making WETH-USDC, the top depth tolerance setting for USDC is 1000, and the current bid side order book looks like this..

(Price/Order size)
- 155.11/0.1
- 155.10/1.0
- 155.00/10
- 154.00/12

In this case, the new bid order (assuming it's profitable) will be made at 155.01. What the pricing algorithm does is to calculate the cumulative volume of the order book entries in quote asset. It'll keep going until the top depth tolerance is exceeded and make an order just above that point. So it'll basically calculate this...

(Price/Cumulative quote volume)
- 155.11/15.511
- 155.10/170.611
- 155.00/1720.611
...

At 155.0, the cumulative quote volume went over the top depth tolerance (1000 USDC). So it'll create an order just above it at 155.01 USDC.

**Comment by martinkou** [comment]
Min profitability is, counter-intuitively, not taken into account when deriving the optimum order price.

But this makes sense because the order price algorithm is already trying to go for as wide a price as possible - if you can't make a profit at that point, then it's better not to do anything.

When the min profitability comes into play is when the strategy is trying to determine the order size - which may be 0 if the order is deemed not profitable at all.

Let's use our example of the buy limit order being proposed at 155.01 USDC.

After the XEMM calculated the proposed price, it'll calculate a proposed hedging price with the min profitability factor. Let's say that factor is 0.005 which is 0.5%.

```
hedging price = limit bid price * (1 + min profitability factor)
= 155.01 * 1.005
= (approx.) 155.78
```

It'll then look to the taker market's bid order book, and try to count how much volume there is if it tries to sell until it hits 155.78.

If the taker market's bid order book is below 155.78 already, then the strategy would reason that it cannot do any hedging trade on the taker market at the min profitability level, and it'll propose an order size of 0 and do nothing.

If OTOH, the taker market's bid order book starts from a higher price like 156.11... then it'll count all the sellable volume between 156.11 down to 155.78, and use that as the basis for proposing the order size.

There's still some more details involved in `cross_exchange_market_making.pyx`. But the above description is basically the overall thinking behind it.

**Comment by carlolm** [comment]
Thanks
