### ISSUE TITLE
[BUG] Inventory skew not working correctly

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1595]
**Describe the bug**

The inventory skew feature does not work correctly when :

1. There are open orders created outside the Hummingbot instance which results to
2. Balances deducted from the total balance (available balance)

Below is the expected behavior :

<img width="328" alt="putty_PStTNLRcQR" src="https://user-images.githubusercontent.com/50150287/78667770-1c532180-790c-11ea-9ea2-54579f5467be.png">

I placed an open order on purpose in Binance so that my available balance will change. Then it started placing a sell order instead.

<img width="329" alt="putty_LvGGV4e50t" src="https://user-images.githubusercontent.com/50150287/78668505-61c41e80-790d-11ea-8c0a-b9f2b48ec1cf.png">

**Steps To Reproduce**

1. Run a pure market making bot with inventory skew enabled
2. Check the orders placed by Hummingbot
3. Manually place a limit order in the exchange with very wide spreads so it doesn't get filled
4. Confirm available balance is changed and that the orders being placed now are different

**Release version**

`0.25.0`
`dev-0.26.0`

**Comment by dennisocana** [comment]
Same thing happens when you have a lot of hanging orders + inventory skew enabled.

**Comment by mifeng** [comment]
This is expected behavior and by design. Inventory Skew only manages the active orders that are refreshed every refresh cycle and doesn't consider hanging orders or orders that the user manually places.

Hanging orders is a different style of market making. The orders left hanging would help the MM's inventory position stay balanced if they are filled. Therefore, hanging orders serve the same purpose as Inventory Skew. I recommend that users use one or the other, but not both simultaneously.
