### ISSUE TITLE
[BUG] orders never initialize on binance in cross market strategy

### ISSUE THREAD

**Issue by sundanny26** [CoinAlpha/hummingbot#1603]
**Describe the bug**
![image](https://user-images.githubusercontent.com/16617597/78833404-3439ac80-79c3-11ea-8093-179563ae3afa.png)
Im having an issue running cross_market strategy. Im in master, order_book_initialized never goes to True. And it gets stuck in here. I've tried with different configurations. Do you know what can this be ?

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Run master branch cross market strategy using binance at both points

**Comment by Clint-G13** [comment]
@sundanny26 Can you send us over your strategy file and also, I want to verify if you are using the same pair for maker and taker. I just made some test and this behavior occurs if you use the same token pair as both taker and maker on the same exchange which will be redundant as you are hedging the same price that's already in that market. Here's a test I made using a different token pair. Take note that I don't have enough balance which is why there are no open order however the order book has initialized also this is where triangular arbitrage comes in ([cross exchange + manual rebalance](https://hummingbot.io/blog/2019-09-strategy-hacks/)):
![XEMM same exchange](https://user-images.githubusercontent.com/57189990/78843139-8c5cc700-7a34-11ea-8594-96580f236731.PNG)
