### ISSUE TITLE
[BUG] Incorrect values in `history` command on Kraken

### ISSUE THREAD

**Issue by gioacchinopoletto** [CoinAlpha/hummingbot#1671]
**Describe the bug**
I receive wrong `Total Trade Value` Delta and `Return %`.

**Steps To Reproduce**
- exchange: Kraken;
- strategy: PMM;
- coins couple: XXBT / ZEUR;
- order amount: 0.002 (minimum on Kraken);
- bid / ask spread: 0.5;

Here are the steps to reproduce the issue (see attachments in the section below):
1. Start PMM strategy 
2. Run history command;

**Screenshots**
See on attached files

**Release version**
0.26.0 / Linux (Docker)
 
**Attachments**
- log file;
- config file (renamed to txt for upload);

**Optional: your discord username:** gioacchino.poletto
![Screenshot](https://user-images.githubusercontent.com/63120138/80315950-3beab500-87fb-11ea-975f-8894f51a197f.png)
![Screenshot_2](https://user-images.githubusercontent.com/63120138/80316022-a996e100-87fb-11ea-8ad8-1d48c42a8d17.png)
[kraken_xxbt-zeur.txt](https://github.com/CoinAlpha/hummingbot/files/4536190/kraken_xxbt-zeur.txt)
[logs_kraken_xxbt-zeur.log](https://github.com/CoinAlpha/hummingbot/files/4536192/logs_kraken_xxbt-zeur.log)

**Comment by dennisocana** [comment]
@vic-en I'm reopening this issue instead of creating a new one. Today the Kraken bot's kill switch was triggered and it says I lost 539 USDC which I don't have. Looking at the `history` output, the Net Delta and Trade Delta for BTC are different which might have been the cause since 0.0656 BTC is equivalent to around 600 USDC.

<img width="371" alt="kraken_btc-usdc" src="https://user-images.githubusercontent.com/50150287/87645860-a9fea280-c780-11ea-8c50-bbaf431a6c2f.png">

<img width="539" alt="exported_trades" src="https://user-images.githubusercontent.com/50150287/87646049-dca89b00-c780-11ea-9c89-4d1bae09ebfa.png">
<img width="607" alt="chrome_gisCBnfOXM" src="https://user-images.githubusercontent.com/50150287/87646053-df0af500-c780-11ea-97c0-875b5ba53816.png">

I tried on Binance using the same pair and does not show the same behavior.

<img width="448" alt="binance_btc-usdc" src="https://user-images.githubusercontent.com/50150287/87646126-f77b0f80-c780-11ea-83c5-45416088d17e.png">

[logs_kraken_btc-usdc.log](https://github.com/CoinAlpha/hummingbot/files/4930234/logs_kraken_btc-usdc.log)
[2020-07-14_kraken_btc-usdc.log](https://github.com/CoinAlpha/hummingbot/files/4930236/2020-07-14_kraken_btc-usdc.log)
[hummingbot_trades.zip](https://github.com/CoinAlpha/hummingbot/files/4930239/hummingbot_trades.zip)

Version `dev-0.30.0`
Running on AWS instance via Docker
```
"branch": "development",
"commit": "025bcdb658be16d3a74a4e3f3736d1b5c83d4ece",
"date": "2020-07-16T01:28:40Z",
"maintainer": "CoinAlpha, Inc. <dev@coinalpha.com>"
```
