### ISSUE TITLE
[BUG] PMM | Kraken not working as a price source

### ISSUE THREAD

**Issue by Clint-G13** [CoinAlpha/hummingbot#1679]
**Describe the bug**
Kraken doesn't take effect as price source in pure_market_making

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market making strategy
2. Set the desired configuration
3. Enable external price feed and select `Exchange`
4. Set Kraken as the external price source.
5. Set the external market symbol to the corresponding token pair set.
6. Run strategy and compare the best bid and ask price.

Note: This happens both paper_trade and live trade
**Screenshots**

![USDC-USDT config](https://user-images.githubusercontent.com/57189990/80563230-058c8000-8a1d-11ea-8c5c-bb0ec0f48ea2.PNG)

![USDC-USDT](https://user-images.githubusercontent.com/57189990/80563244-0cb38e00-8a1d-11ea-9a28-213916fe792b.PNG)

Binance Orderbook
![USDC-USDT screenshot](https://user-images.githubusercontent.com/57189990/80563253-1210d880-8a1d-11ea-8aaf-a096460919bf.PNG)

Kraken Orderbook
![kraken](https://user-images.githubusercontent.com/57189990/80563373-89df0300-8a1d-11ea-9f73-5ef3ae7ea152.PNG)

**Release version**
0.26.0 and 0.27.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by Clint-G13** [comment]
Live trade using XRP-BTC and price source market XXRP-XXBT, bot still uses Binance price instead of Kraken.
![XRP](https://user-images.githubusercontent.com/57189990/80564198-c14eaf00-8a1f-11ea-9945-b15fc9c88b82.PNG)

**Comment by dennisocana** [comment]
I think it's working. So far I only tested in paper trade mode. It's hard to see the difference because both markets you're using for the test are almost of the same prices, unless you calculate your expected maker order prices manually.

So I did an XRP-BTC market in Binance without pricing source first, see screenshot below.

![75pj5jngsJ](https://user-images.githubusercontent.com/50150287/80565134-52268a00-8a22-11ea-8200-aaf2b7388303.png)

Then I enabled pricing source to use a completely different market in Kraken like XETH-XXBT on purpose to see the change in prices.

![qnjZVqULoB](https://user-images.githubusercontent.com/50150287/80565194-74b8a300-8a22-11ea-8a52-4fa7043fad74.png)

You can try if this also happens in live trade.

**Comment by dennisocana** [comment]
I think another good feature to add is to show in `status` output when the bot is using an external pricing source and the mid price reference of the orders.

**Comment by Clint-G13** [comment]
Confirm that the external price source is working correctly after doing a manual computation for the order price. Indeed, a feature to display the external price and mid-price is good to avoid confusion.
