### ISSUE TITLE
[BUG]PMM| Status command display 0 balance after starting the bot

### ISSUE THREAD

**Issue by devoger** [CoinAlpha/hummingbot#1690]
**Describe the bug**
// A clear and concise description of what the bug is.

Running status command after enabling inventory skew result to 0 balance in Huobi Live trading.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):

This is live trading.

1. Create PMM strategy
2. Choose Huobi connector and enter your API keys
3. Run start command
4. Run stop 
6. You can enable/disable some configs like Inventory Skew
6. Start the bot
7. Run status command

The result show 0 balances.

![Screen Shot 2020-05-04 at 16 10 20](https://user-images.githubusercontent.com/8411294/80947026-e0837d00-8e21-11ea-8eb6-f38e017c2366.png)

8. Run status command the second time and your balances will display

![Screen Shot 2020-05-04 at 16 08 48](https://user-images.githubusercontent.com/8411294/80946903-ad40ee00-8e21-11ea-92f6-5af5c058c8ce.png)

...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

![Screen Shot 2020-05-04 at 16 11 47](https://user-images.githubusercontent.com/8411294/80947118-0c066780-8e22-11ea-9b9b-fd71a691261c.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

0.26.0 / Docker Build

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[logs_conf_pure_mm_2.log](https://github.com/CoinAlpha/hummingbot/files/4573484/logs_conf_pure_mm_2.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rennel-tabing** [comment]
I am unable to reproduce this behavior on version dev-0.27.0

![image](https://user-images.githubusercontent.com/53868268/80960785-8d84d800-8dd7-11ea-8442-8100c0263bf4.png)

On docker Build 0.26.0
I am unable to reproduce this behavior since I run into a different issue related to 
https://github.com/CoinAlpha/hummingbot/issues/1678

**Comment by devoger** [comment]
I can reproduce the same behavior using dev-0.27.0.
The issue also occurs with just the default configurations.

1. Just select Huobi
2. Define spread
3. Connect API keys
4. Run start and stop several times (2-3x minimum)
5. Then run Status command

![Screen Shot 2020-05-05 at 19 37 08](https://user-images.githubusercontent.com/8411294/81062011-e05dad00-8f07-11ea-9ab8-60960c538374.png)

Here is a video of the bahavior:

https://www.dropbox.com/s/13dfjg5d6kc4iak/Screen%20Recording%202020-05-05%20at%2019.28.24.mov?dl=0

**Comment by Clint-G13** [comment]
From my initial test, I was able to reproduce the 0 balance together with the error on the logs by quickly running the `status` command upon starting the strategy, and somehow the balance info is delayed which is why we see the 0 value. If you start your bot and wait for a few seconds before running the status command, you won't see the 0 value. On my second test, I was able to replicate the cause of the error on the logs, however, the 0 balance is no longer appearing on my side.

The error on the logs typically occurs when you run the status command twice within the second as shown on the image.
![test](https://user-images.githubusercontent.com/57189990/81254699-70156f80-905e-11ea-92d5-8534c9527f24.PNG)
