### ISSUE TITLE
[BUG] Unable to create pure_market_maker on Binance

### ISSUE THREAD

**Issue by CrackLord** [CoinAlpha/hummingbot#1721]
**Describe the bug**
When trying to create a market maker for Binance, an error appears when selecting the amount per order. Error appears:
`Unhandled error in background task: type NoneType doesn't define __round__ method`

**Steps To Reproduce**
Running the following commands to create the error:
1. `create`
2. `pure_market_making`
3. `binance`
4. `RLC-BTC`
5. `1.2`
6. `1.2`
7. `15`
8. `30`

**Screenshots**
![image](https://user-images.githubusercontent.com/31401036/81494163-cc6ad000-92a6-11ea-9704-6f50ffc97b62.png)

**Release version**
0.26.0

**Comment by CrackLord** [comment]
Ah, fixed by having some BTC, maybe a friendlier error message here would be useful?

**Comment by PtrckM** [comment]
Apologize for the inconvenience. Yes correct, on version [0.26.0](https://docs.hummingbot.io/release-notes/0.26.0) skew is enabled by default, bot analyze your current balance to check your inventory split and ratio for eg. `On binance, you have 106.1975 RLC and 0.0022 BTC. By market value, your current inventory split is 65. 2% RLC and 34.8% BTC. Would you like to keep this ratio? (Yes/No) >>>` that's why you're getting an error and cannot past the order amount, this was fix on the next version currently development [dev-0.27.0](https://github.com/CoinAlpha/hummingbot/tree/development) and disabled the skew by default

**Comment by mifeng** [comment]
@PtrckM Please clarify if this bug still exists on `development` - its not clear from the comment above.

**Comment by PtrckM** [comment]
By default when using Binance on PMM strategy the skew feature was enabled that's why the user unable to get pass the order amount.

**Note**: using API+key on binance no balance as per user

![image](https://user-images.githubusercontent.com/54516858/81911581-1c77c880-9600-11ea-854f-fc881324c630.png)

on development version dev-0.27.0
![image](https://user-images.githubusercontent.com/54516858/81911715-4335ff00-9600-11ea-95e6-0e9e44df946c.png)
