### ISSUE TITLE
[BUG] Multiple order levels: numbers of orders alternating between refreshes

### ISSUE THREAD

**Issue by carlolm** [CoinAlpha/hummingbot#1747]
**Describe the bug**
Bots with multiple order levels (3): for every refresh, the bot seems to alternative 1, 2, and 3 order levels with each refresh, on both sides.

Expected behavior: always have 3 order levels on each side.
The inventory skew range is 0-100%.

**Steps To Reproduce**
- bots setup with order level = 3
- inventory skew enabled for 50%

![image](https://user-images.githubusercontent.com/12274903/81882267-25f12a00-9547-11ea-92fe-07f1950287a5.png)

![image](https://user-images.githubusercontent.com/12274903/81882275-2ab5de00-9547-11ea-8f8c-d829d743b0a5.png)

**Release version**
0.26.0

**Attachments**
[logs.zip](https://github.com/CoinAlpha/hummingbot/files/4625534/logs.zip)

**Comment by Nullably** [comment]
After a lot of debugging, here is what I think happened.
- First of, `InventorySkewMultipleSizeSizingDelegate` relies on getting accurate real time available balance (and current active orders volume) to work out order proposal sizes.
- Most of the time, this works fine, our Binance market connector uses web socket connection to get real time balances (available and total)
- For some reason, after running the bot for a while, the connector network stops and starts again. Actually this happens more often than I think it should.
- The connector tries to reconnect, but web socket connection for the user info never reconnects successfully. (`BinanceAPIUserStreamDataSource`)
- Binance connector has a back up `_update_balances` which uses REST API to get balance information, however this is lagging. Thus, the available balance is lower than actual (not accounted for amount from canceled orders). 
-  The sizing delegate then generates fewer order sizing proposal and often alternates depending on whether there are currently active orders at the time of calculation. 

One way to reproduce this bug is to force the connector to set NOT_CONNECTED status after it started for while, e.g. update `check_network` function as following:
```
async def check_network(self) -> NetworkStatus:
        try:
            await self.query_api(self._binance_client.ping)
            self._check_network_cnt += 1
            if self._check_network_cnt == 7:
                return NetworkStatus.NOT_CONNECTED
        except asyncio.CancelledError:
            raise
        except Exception:
            return NetworkStatus.NOT_CONNECTED
        return NetworkStatus.CONNECTED
```

**Comment by Nullably** [comment]
So there are actually a number of issues from this.
- `BinanceAPIUserStreamDataSource` does not reconnect.
- `InventorySkewMultipleSizeSizingDelegate` is not going to work for exchanges which do not provide web socket connection for user balance update.
- `InventorySkewMultipleSizeSizingDelegate` uses a list active orders which is dynamically changing, at the time of sizing calculation, active orders might be in the middle of cancelation process. This results in inaccurate total balance.
