### ISSUE TITLE
[Refactor] Simplify market connector fee logic

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1779]
Currently, our market connectors have logic to precisely track the coin used to pay for fees and whether it's taken out of the base or quote token. In addition, there is special logic to handle Binance, which used to handle fees different from other exchanges.

Binance has now adjusted their fee logic to match other exchanges so that the fee is always paid in the quote token (or in BNB if the user turns that on), so we don't need the extra Binance logic now. Also, the exact fee coin doesn't materially impact profitability, which is the most important metric. Adopting a simpler model for calculating fees will make the codebase simpler to maintain.

## Tasks
* Standardize how fees are calculated across all market connectors so that there's a maker fee  (% of order amount), taker fee (% of order amount), and a flat fee for each market (the flat fee will be zero for all centralized exchanges, and is used only for Radar Relay gas currently).
* Assume that both fees are always paid using the quote asset
* Remove the Binance fee handling logic
* In `fee_overrides`, let users override maker, taker, and flat fees for each exchange

**Comment by Nullably** [comment]
We currently assume market order is a taker order and limit order a maker order, this is not always the case for limit order. A limit order can be either maker or taker depending on whether the order matches at submission.
I think this should be fixed in `c_get_fee` method, instead of `OrderType` use `is_maker` argument.

**Comment by Nullably** [comment]
To clarify more on my thoughts on fees.
- Whether an order is a maker or a taker should be considered separately from Limit/Market order types.

- Fees can thought of in 2 stages, before or after a trade happens. Before a trade, this is like an estimation of what the fee is going to be, this is usually needed to whether to place an order and by how much. The strategy knows beforehand whether an order is gonna be a maker or taker. For after a trade happens, we can usually get precisely how much fee is charged for the trade, in case of Binance, this information is available for both REST API and web socket. 
For our Binance connector, I am not sure why we replace this info with `c_get_fee`, as can be seen on line 621 in `binance_market.pyx`  

- As a side, I think we should not use market order type at all, as it is risky and can be taken advantaged of by other types of trading strategies. I suspect that is one of the reasons why users report losing money on xemm strategy. We currently submit the taker side of the trade as a market order. When we fix this, ie. use a limit order instead of a market order, we can no longer consider the fee by order type.

**Comment by Nullably** [comment]
My recommendation:
- Rename `c_get_fee` to `c_estimate_fee` (and `get_fee` as well), this is to clearly identify what the function does. And as per requirement, this is the part where we can simplify. And its only argument is `is_maker`. It returns a percentage fee for CEXes and a flat fee for DEXes. And the values can be overridden by fee_overrides configuration.
- After trade happens, this is where we can get the actual fee. For Binance, this info is there in the API responses, we store it as is (as a flat fee in TradeFee object). There is no need to call get_fee here. A minor change is needed in performance analysis to handle when the.flat fee is other token than the quote token. Apply a similar approach for other connectors.
- Review where `c_estimate_fee` are called, I think this is mostly in strategies, and history command and update them accordingly.

**Comment by Nullably** [comment]
I created this issue for the part where fees are not stored correctly.
https://github.com/CoinAlpha/hummingbot/issues/2084
