### ISSUE TITLE
Bot sells all stocks $

### ISSUE THREAD

**Issue by 3loyWiking** [CoinAlpha/hummingbot#184]
**Describe the bug**
Bot sells all stocks $

**Steps To Reproduce**

1) I set up an arbitration strategy for Binance & RadarRelay. At Binance I have 50% in ETH & 50% in USDC
On RadarRelay, I have 50% in WETH & 50% in DAI

2) I turned on the bot and left it for 24 hours, when I came, I see that the bot sold all the stocks of USDC & DAI and bought ETH.

**Screenshot**
![Снимок экрана от 2019-05-07 15-13-13](https://user-images.githubusercontent.com/8113799/57279107-beee9900-70da-11e9-9f4c-21209f4add20.png)

(https://github.com/CoinAlpha/hummingbot/files/3151087/hummingbot_logs_2019-05-06-20-17-51.log)

**Comment by yzhang1994** [comment]
@3loyWiking This is likely due to an issue with submitting market orders on Radar Relay, which causes one leg of the arbitrage to fail. Since Radar uses an open order book, there is a high chance of order collision and market orders often fail as a result. 

Our engineers are working with Radar to come up with a solution. However, in the near term, it might be good to avoid submitting market orders on Radar.

**Comment by 3loyWiking** [comment]
@yzhang1994 could you send me more information about "order collision" please..?

**Comment by mifeng** [comment]
@3loyWiking Here's a twitter thread from Antonio Juliano from dy/dx about collision issues on Radar Relay: https://twitter.com/AntonioMJuliano/status/1070772120894922752
