### ISSUE TITLE
[Research] Assess Infura usage when using Hummingbot on DEXs

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1848]
Due to recent changes in rate limits by Infura, user report that Hummingbot clients running PMM with basic settings now hit the daily 100k limit in approx 21 hours.

Assess how severe this issue is by running various bot configurations for 1 hour each and assessing how many Infura calls are made over that time. The main params that affect number of Infura calls should be:
- number of order levels
- order refresh time
- other params that increase number of markets tracked or API calls made

**Comment by wpenn** [comment]
For Infura's free "Core" account,  they restrict the number of Requests/Day to 100,000. Otherwise, you have to pay at least $50/month. 

We are therefore restricted to about 4,166 requests per hour. After some testing with our PMM strategy on Radar Relay, our client calls Infura ranging from 4000 - 6000 times per hour, depending on the configuration. `order_refresh_time` of less than 60 seconds and an `order_level` greater than 1 easily results in a rate higher than 4166. 

**Top Infura Method Calls:**
- `eth_getLogs`: 39.38%
- `eth_getBlockByNumber`: 19.47%
- `eth_call`: 14.91%
- `eth_getBlockByHash`: 12.71%
- `eth_getBalance`: 5.58%
- `eth_gasPrice`: 5.50%
- `eth_accounts`, `eth_getTransactionCount`, `eth_blockNumber`: < 2.00%

**Infura Usage Data from Past 24-hours**
(Only ran bot for 7 Trials [19 hours total Maximum])
<img width="1091" alt="Screen Shot 2020-06-12 at 4 55 37 PM" src="https://user-images.githubusercontent.com/20906874/84545607-8e116800-accd-11ea-895f-cdba7c091028.png">

**Comment by gabririgo** [comment]
a hint for reducing smart contract calls is using helper contracts like the following any time multiple requests are sent for the same operation:
[https://github.com/RigoBlock/rigoblock-monorepo/blob/master/packages/contracts/src/examples/helpers/HGetMultipleBalances.sol](url)

Ofc logs, which are the biggest number of calls here, can be reduced only by substituting log queries with transaction queries and filters, or, as already discussed with @mifeng , by properly optimizing the code.
