### ISSUE TITLE
Heat Map of trading locations

### ISSUE THREAD

**Issue by marexigroup** [CoinAlpha/hummingbot#1874]
**Feature Suggestion**
Could we create a location heat map of where all the bots are based?

**Impact**
This gives you an idea of how "decentralized" the network is already and how trading behavior might result.

**Comment by Oriolfs** [comment]
Can it actually be trully done? I mean, people can be running cloud instances in any part of the world and not be the real location.
I also think it's not really useful information to be in the bot, maybe a new Tab in the Miners App(Markets - Activity - Map - Leaderboard - Etc).

**Comment by mifeng** [comment]
Interesting suggestion - agree with @Oriolfs that it's not really useful info.

However, we do get pings from clients who agree to the "Send error logs" question when they install Hummingbot. We could potentially add another option to "Share my location" in order to produce a heat map.

Anecdotally, our user base is very global, so our would also find it interesting to see where our users are based.
