### ISSUE TITLE
[BUG] Hanging orders is broken in v0.28

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1890]
**Describe the bug**
Hanging orders mode is broken in v0.28.0 after the redesign of the PMM strategy.

This [spreadsheet](https://docs.google.com/spreadsheets/d/1UCsBcgQwvIXQ8-VIwtH4VjQqw8TzIyHSZTPeq6LoDQc/edit?usp=sharing) shows the correct behavior in v0.27 (tested on Binance) vs the behavior in v0.28 (tested on Kraken)

Configs:
- BTC/USDT
- 2 order levels
- hanging orders ENABLED

[logs_v0.27.log](https://github.com/CoinAlpha/hummingbot/files/4807012/logs_v0.27.log)
[logs_v0.28.log](https://github.com/CoinAlpha/hummingbot/files/4807013/logs_v0.28.log)

**Comment by Nullably** [comment]
The expected behaviour in hanging orders in multiple order mode is when an order is filled, all orders on the other side are left hanging. Example:
- S2
- S1
- B1
- B2
When B1 gets filled, both S1 and S2 are left hanging on the orders, upon filled_order_delay:
- S2 (new)
- S2 (hang)
- S1 (new)
- S1 (hang)
- B1 (new)
- B2 (new)

For v 0.27, I confirmed this behaviour via code inspection and @dennisocana confirmed this in testing.
For v 0.28, I confirm this behaviour is working as v 0.27 on Binance as below 

<img width="627" alt="Screenshot 2020-06-22 at 10 59 52 AM" src="https://user-images.githubusercontent.com/37262506/85244934-a2492800-b478-11ea-9134-878894fbe232.png">
<img width="570" alt="Screenshot 2020-06-22 at 10 59 57 AM" src="https://user-images.githubusercontent.com/37262506/85244932-a1b09180-b478-11ea-9383-4f6cd078b957.png">
<img width="587" alt="Screenshot 2020-06-22 at 11 00 43 AM" src="https://user-images.githubusercontent.com/37262506/85244928-9f4e3780-b478-11ea-95e6-119b41d5a8ed.png">

**Comment by Nullably** [comment]
There seems to be issues with Kraken connector.

1. Errors in `logs_v0.28.log` attached log file, I have not yet abled to reproduce these.

2. Best bid price and best ask price are not updated as the underlying order book.
<img width="237" alt="Screenshot 2020-06-22 at 10 50 19 AM" src="https://user-images.githubusercontent.com/37262506/85245327-ceb17400-b479-11ea-848f-a40a38c45565.png">
<img width="639" alt="Screenshot 2020-06-22 at 10 50 12 AM" src="https://user-images.githubusercontent.com/37262506/85245333-d244fb00-b479-11ea-9eb4-c4b17dbc4676.png">
I'm going to investigate this further.

**Comment by Nullably** [comment]
I have created 2 issues related to this issue
#1901 
#1902 

I have yet abled to reproduce this below error in the attached log 
` OSError: {'error': {'error': ['EAPI:Invalid nonce']}} `logs_v0.28.log`

**Comment by mifeng** [comment]
Thanks @Nullably for finding the cause. I will close this issue in favor of #1901 and #1902
