### ISSUE TITLE
[BUG] OSError-Error Fetching Data

### ISSUE THREAD

**Issue by nsshommo** [CoinAlpha/hummingbot#192]
**Describe the bug**
OSError- During handling of the above exception, another exception occurred. Error fetching data, too many requests, please try again later.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: Cross Exchange MM, Maker: RadarRelay, Taker: Binance
2. Start the bot using this command: Config, Start

**Screenshots**
![hummingbot_bug_2](https://user-images.githubusercontent.com/31445351/57394621-c64f9880-71e7-11e9-8909-a49d1bb375e7.png)

**Release version**
Version: 0.5.0

**Attachments**
N/A

**Comment by mifeng** [comment]
This error message is caused by hitting API rate limits on Radar Relay. Some additional info will help us figure out if this is an issue that we can address via code:
* log file
* strategy config file
* [question] are you running multiple instances of Hummingbot?
* [question] are your colleagues running Hummingbot concurrently from the same IP address?

**Comment by martinkou** [comment]
Were you running multiple instances of hummingbot on the same machine, and connected to Radar Relay?
