### ISSUE TITLE
[BUG] HB displays inconsistent token symbols and trading pairs.

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#1922]
**Describe the bug**
Hummingbot displays inconsistent token symbols and trading pairs. 
For example:
When configuring `market` for Kraken exchange
![image](https://user-images.githubusercontent.com/37262506/85498813-fe47b400-b612-11ea-9df8-8a16af76afeb.png)

Up on `status` 
![image](https://user-images.githubusercontent.com/37262506/85498693-c2145380-b612-11ea-941d-48a05d03a494.png)

In the log
![image](https://user-images.githubusercontent.com/37262506/85498863-161f3800-b613-11ea-986b-393f3dab5d42.png)

This also applies to other exchanges, e.g. Binance, to certain extent.

For Binance, market symbol displays with "-", but in some cases without.
![image](https://user-images.githubusercontent.com/37262506/85499105-947bda00-b613-11ea-8d63-85fabc8e002f.png)

Notes:
- To fix this, we'll need to update most of our connectors. Convert symbols to exchange format upon calling its APIs and convert symbols to HB format on the returned API values. 
- Store these symbols locally in HB format with all capital letters for token symbols with "-" separator between base symbol and quote symbol, e.g. BTC-USDT.
- Update developer manual to clarify these conversion steps
- Include basic unit testing for the conversion functions.

**Comment by mifeng** [comment]
@Nullably This is a large change, but I think we may want to do this work before we start pushing external development. We have lots of issue with trading symbols, and they will only get bigger as we add more exchanges unless we standardize on a certain convention.

**Comment by vic-en** [comment]
@Nullably @mifeng 
I already started work on this. Just want to suggest a simple alternative to the approach of solving this problem which says:
`To fix this, we'll need to update most of our connectors. Convert symbols to exchange format upon calling its APIs and convert symbols to HB format on the returned API values.`
This approach would affect alot of files to get done and may cause confusion for new connector developers. 

I already accessed the files to be changed and want to suggest an alternative of just modifying parts of HB that logs/prints those pairs. Basically, the logger in each connectors and strategies, plus the `format_status` methods of each strategy. This approach is also good as the chances of having a bug is slim because no core part of HB will be modified. Since the main thing this issue is trying to address is to mainly let users see a consistent pair, I advise this approach.

Let me know what you guys think.

**Comment by Nullably** [comment]
@vic-en This problem is not just for the users, it's also affecting us developers. When we look at the code, We don't know what format of the trading pair is to be expected. Exchange trading pair symbols are in various formats from having lower case for symbols to having quote first before base. It's best if exchange connectors maintain their own trading pair format internally (within the connector module), but when communicating with other parts of the system, the standardised/unified format should be used.

**Comment by vic-en** [comment]
> 
> 
> @vic-en This problem is not just for the users, it's also affecting us developers. When we look at the code, We don't know what format of the trading pair is to be expected. Exchange trading pair symbols are in various formats from having lower case for symbols to having quote first before base. It's best if exchange connectors maintain their own trading pair format internally (within the connector module scope), but when communicating with other parts of the system, the standardised/unified format should be used.

Okay, I get that. I'll go on to modify all necessary files.
