### ISSUE TITLE
[BUG] Best price on one side not updating on Kraken

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1926]
**Describe the bug**

Similar to issue https://github.com/CoinAlpha/hummingbot/issues/1901 , one side either best bid or best ask is not in sync with the actual prices in orderbook. No errors found in logs.

**Steps To Reproduce**

1. Run a pure market making strategy on Kraken on any trading pair
2. Run `status` command every second and compare side by side with Kraken orderbook

**Screenshots**

<img width="960" alt="putty_MNprdhnJAG" src="https://user-images.githubusercontent.com/50150287/85540525-ae381400-b649-11ea-8894-ec0dddd195cd.png">

**Release version** : 0.28.0

**Comment by Nullably** [comment]
I think what happened is the way the connector applies order book difference upon receiving web socket messages.
In case of Kraken (and most CEX connectors), the connector uses REST API to get order book snapshot before applying the difference upon receiving web socket messages. The problem is during the gap time between those two events, the order book might have gone through changes, and the bot will miss out on those changes. The web socket order book diff messages should apply only on the snapshot from the web socket (usually the first message upon opening the socket connection).

In case of Kraken, the issue is much more visible as the connector subscribes to all exchange available markets for `trade` and `orderbook` in the web socket connection.

**Comment by Nullably** [comment]
To reproduce this error, you might need to stop and start the bot a few times to wait for the incident happens. I think if we could see the current state of the order book in HB more easily, e.g. using `orderbook` command, it'll help in identifying this issue.

**Comment by dennisocana** [comment]
Fixed with https://github.com/CoinAlpha/hummingbot/pull/1921
