### ISSUE TITLE
[BUG] Inconsistent adjusted order amount with inventory skew

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2058]
**Describe the bug**
Every time order refresh, the adjusted order amount in Eterbase exchange changes even if there are no filled trades.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market making strategy
2. Set exchange to Eterbase
3. Disable ping-pong
4. Disable order_refresh_tolerance_pct
5. Enable inventory skew, you can use the default skew value or set different inventory_target_base_pct.
6. Start strategy and wait for orders to refresh.
7. Check adjusted order amount value on the status window and logs and you will notice that it changes every time order gets refreshed.

**Screenshots**
![eterbase](https://user-images.githubusercontent.com/57189990/87621442-6772a100-c753-11ea-8159-050f57d6ddaa.png)

**Release version**
0.29.0 and 0.30.0

**Attachments**
[logs_Eterbase.log](https://github.com/CoinAlpha/hummingbot/files/4929049/logs_Eterbase.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by dennisocana** [comment]
This is caused by the broken balance update as mentioned here in https://github.com/CoinAlpha/hummingbot/issues/2012. Inventory skew uses the available balance instead of the total balance https://github.com/CoinAlpha/hummingbot/issues/1927. Changing issue title since this is not isolated to Eterbase connector. See screenshot below from Liquid.

![image](https://user-images.githubusercontent.com/50150287/87629397-8e39d300-c765-11ea-8bda-21f48fcd54f8.png)

**Comment by gabririgo** [comment]
+1 on bamboorelay

**Comment by sdgoh** [comment]
#2224
