### ISSUE TITLE
[BUG] script folder is empty after install or update

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#2065]
**Describe the bug**
 - Script folder is empty after installation or update. 
- affected build Windows & Mac Binary installer and docker builds

using docker scripts [create.sh](https://raw.githubusercontent.com/CoinAlpha/hummingbot/development/installation/docker-commands/create.sh) or [update.sh](https://raw.githubusercontent.com/CoinAlpha/hummingbot/development/installation/docker-commands/update.sh) for docker builds.

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/87668880-8c8d0100-c79f-11ea-93f1-917a03f116c6.png)
![image](https://user-images.githubusercontent.com/54516858/87668897-96aeff80-c79f-11ea-9885-fa297c6a842a.png)
![image](https://user-images.githubusercontent.com/54516858/87668948-adeded00-c79f-11ea-9573-9ef80f2a0424.png)
![image](https://user-images.githubusercontent.com/54516858/87669656-f5c14400-c7a0-11ea-8ff2-7ceec2827eff.png)

**Release version**
0.29.0

Workaround:
 - manually place [scripts](https://github.com/CoinAlpha/hummingbot/tree/master/scripts) into the script folder

![image](https://user-images.githubusercontent.com/54516858/87670908-19858980-c7a3-11ea-88e7-f2f750b13493.png)
![image](https://user-images.githubusercontent.com/54516858/87670946-24401e80-c7a3-11ea-9364-a076c5125cd9.png)

**Comment by dennisocana** [comment]
@PtrckM this is the current expected behavior. User shouldn't use the scripts feature on binary - see warning in [release notes](https://docs.hummingbot.io/release-notes/0.29.0/#new-feature-scripts) or else they'll get this https://github.com/CoinAlpha/hummingbot/issues/2034.

The `hummingbot_scripts` folder when installing via Docker is expected to be empty for now. If users wants to use the sample scripts via Docker they have to clone from the repo or copy.

**Comment by PtrckM** [comment]
got it thanks

**Comment by dennisocana** [comment]
@PtrckM you can add in the docs how users on Docker can get the sample scripts into the `hummingbot_scripts` folder.
https://docs.hummingbot.io/advanced/scripts/
