### ISSUE TITLE
[Feature] Disable balance limit from the Hummingbot client

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2219]
**Describe the bug**

Setting the ``balance limit`` to 0 will limit your balance to 0 instead of removing the limit. The current workaround to remove the limit is to remove the ``balance limit`` value inside the ``conf_global.yml``.

**Steps To Reproduce**

Run a pure market making strategy and set a value of 0 to the balance limit.

**Screenshots**

![image](https://user-images.githubusercontent.com/64377055/90325733-d42ac680-dfb1-11ea-8d6c-4a0fda0ac05f.png)
![image](https://user-images.githubusercontent.com/64377055/90325746-f91f3980-dfb1-11ea-933c-f63587e39bf5.png)

**Release version**
version-0.30.0

```
"branch": "master",
"commit": "7659cfeee8ae7032647b466c335255eed417b084",
"date": "2020-08-11T02:22:37Z",
```

**Comment by Clint-G13** [comment]
It seems that Huobi exchange is not affected by this behavior:
![limit-huobi](https://user-images.githubusercontent.com/57189990/90825549-a8ba2a00-e36b-11ea-85e0-4dae3b7a027a.PNG)
Tested other exchanges except for Bittrex (No account), Liquid (Insufficient balance), and DEX (only shows ETH balance). And they all have the same behavior when balance limit it set to 0.

**Comment by PtrckM** [comment]
https://github.com/CoinAlpha/hummingbot/pull/2354

**Comment by dennisocana** [comment]
Changing ticket from bug report to feature request. Setting the balance limit to 0 allows Hummingbot to not use any balances for a particular asset therefore not creating orders.

We've discussed about the functionality that will allow users to set and remove the limit from the HB client like setting to a negative value instead of editing the global config file to maintain UX.

**Comment by phbrgnomo** [comment]
what about using -1 to remove the limit?
