### ISSUE TITLE
[BUG] Trade size in Hummingbot not correct

### ISSUE THREAD

**Issue by itsmequik** [CoinAlpha/hummingbot#2280]
**Describe the bug**
The trade size are not correct in Hummingbot history for Kucoin. The orders created and executed have the correct size, but are displayed with an incorrect size in the history.
**Steps To Reproduce**
I do cross exchange arbitrage GAS-BTC Kucoin and Binance. The trade size are most of the time not correct for kucoin only in the history. But they are always executed the correct size on kucoin. Seems like Hummingbot is only reading part of the order from kucoin. 

**Screenshots**
![new_hummingbot](https://user-images.githubusercontent.com/22601305/92305429-994ff900-ef87-11ea-808d-5c3ab5bcecb7.JPG)
**history in hummingbot**
![new_kucoinJPG](https://user-images.githubusercontent.com/22601305/92305433-9c4ae980-ef87-11ea-98e6-ebfd3e74a12b.JPG)
**history on kucoin**

**Release version**
0.30.0

**Attachments**
![new_settings](https://user-images.githubusercontent.com/22601305/92305446-d0bea580-ef87-11ea-9c59-1f0cd4d5145c.JPG)
[logs_GAS_BTC_arbi.log](https://github.com/CoinAlpha/hummingbot/files/5178093/logs_GAS_BTC_arbi.log)

**Optional: your discord username:**
itsmequik

**Comment by vic-en** [comment]
@itsmequik 
Thanks for reporting this.
Actually, the reason why it appears KuCoin doesn't display filled order correctly is because the order for KuCoin in the log above was filled twice. The initial one filled 0.0819 of the order and the second filled/completed the remaining amount of the order. So it appears that unlike Binance, KuCoin doesn't send an order filled event along side with the order completion event.

Note that as reported, this doesn't affect the main trading functionality, just the logs.
However, watch out for a fix to this in subsequent releases.
