### ISSUE TITLE
[Feature] Add a Pause/Resume command to HB

### ISSUE THREAD

**Issue by ZeroCool940711** [CoinAlpha/hummingbot#2383]
**Feature Suggestion**
Would be nice to have a Pause/Resume command just like Stop and Start, that way we can pause the bot without losing the active/hanging orders we have already placed on the order book, this will also allow us to pause the bot in cases like what is mentioned on issue #2380, by pausing the bot we give it time to reduce the amount of requests its making to the API, it can also be used to change the configuration while the bot is running without having to stop it, some options can be changed on the fly but pausing the bot before changing those options is safer than doing it while the bot is running in case some mistake is made, after some time we can resume the bot and it will continue trading like normal.  

An idea for this would be making the Pause command accept a value to specify how long in seconds the bot will be paused or if no value is specified then it will be permanently paused until the Resume command is used, when pausing the bot it will only stop it from sending new requests and placing new orders but existing orders will still be on the order book, once the resume command is sent or the time for the pause command has passed it will go back to place orders normally.

**Comment by TheHolyRoger** [comment]
I'd like to build on this - 
Would be nice to also be able to pause and resume **through** a full bot shutdown/restart. Query hanging orders to find out which one's have been filled/still open and take it from there.

Is there anyone else working on or started looking at code for this? I can get my hands dirty but don't want to double up on work.

**Comment by phbrgnomo** [comment]
@TheHolyRoger no member from the core team is working on this feature at the moment, and it is currently on hold. All hands are full right now.

Feel free to implement this. This will be really helpful to other possible features I am researching atm.

**Comment by zappra** [comment]
Pause/resume has also been mentioned as a way of riding out unfavourable trading conditions. In this instance, you might also want the option of cancelling any open orders

**Comment by mifeng** [comment]
Per discussion at weekly meeting, we are pulling this story into the plan for the current release.

To complete this story:

1. Add a flag to the `exit` to prevent bot from cancelling outstanding orders upon exit. This should allow the client to pick up state of those orders when it restarts. Note that by default, Hummingbot tries to cancel "dangling orders" that were not cancelled if it accidentally shut down beforehand. If so, I think we should remove that logic, since it causes more problems than it helps.

2. Make `order_level` configurable on the fly if it is not already. This allows users to run `config order_levels 0` to pause the bot, and `config order_levels 1` to resume again. Afterwards, add a callout note to https://docs.hummingbot.io/strategies/order-levels/ to let users know that they can pause the bot with this command.
 



3. Add a num

**Comment by ZeroCool940711** [comment]
@mifeng I think instead of using `config order_levels 0` to pause it would be easier to understand if it's a `pause command` that does that, just like `start` or `stop`, if you want something more complex the pause command could even be extended later to provide conditions to automatically resume the bot, as mentioned on other issues. Another thing is that for backward compatibility you should keep in mind what the current version of the bot does when exiting, so, if currently when killing the bot the hanging orders are still on the exchange and we update HB to the new version the next time it starts if there are hanging orders on the exchange HB should handle them and continue with those orders instead of canceling them, that way those of us who want to upgrade HB but have hanging orders that we don't want to lose we can upgrade easily and be sure we won't lose them afterwards.
