### ISSUE TITLE
[Feature] Use volume mounts in Docker documentation.

### ISSUE THREAD

**Issue by MicahZoltu** [CoinAlpha/hummingbot#244]
**Feature Suggestion**
The documentation recommends doing `-v "$PWD"/conf/:/conf/ -v "$PWD"/logs/:/logs/` for mounting.  Consider instead having it use [volume mounts](https://docs.docker.com/storage/volumes/) instead of bind mounts for better integration with the Docker ecosystem and cross-platform compatibility (`$PWD` doesn't work on Windows).

**Impact**
While bind mounts are useful for when you want to do some quick and dirty hacking inside of a Docker image, they aren't ideal for running production software, especially when you start to get into multi-host orchestration, swarms, management, etc.  Volume mounts on the other hand are managed by Docker and well integrated into orchestration systems.

----

Verbose volume mount docker run CLI parameters:
```
--mount 'type=volume,source=hummingbot_conf,destination=/conf/'
--mount 'type=volume,source=hummingbot_logs,destination=/logs/'
```
Pithy volume mount docker run CLI parameters:
```
--mount src=hummingbot_conf,dst=/conf/ --mount src=hummingbot_logs,dst=/logs/
```

**Comment by pointtoken** [comment]
Additionally, this would facilitate running in the cloud.

**Comment by carlolm** [comment]
Thanks for the suggestion:
https://github.com/CoinAlpha/hummingbot/pull/338

I have kept the type of mount as `bind`; currently the bot is not designed for use through orchestration/swarms, and requires users to customize instructions for each instance.  Therefore, the files need to be easily accessible on the host machine, rather than accessible via the docker daemon.
