### ISSUE TITLE
Arbitrage doubt

### ISSUE THREAD

**Issue by Vitu02** [CoinAlpha/hummingbot#2475]
Hi, I am new to hummingbot and testing the arbitrage strategy I only get one of the two exchanges in paper_trade mode

![image](https://user-images.githubusercontent.com/72853691/95954998-7a514c00-0dfc-11eb-9d84-fcd658da0c60.png)

My arbitrage conf file:

![image](https://user-images.githubusercontent.com/72853691/95955067-8dfcb280-0dfc-11eb-9980-f73d9d89e05a.png)

**Comment by sigit2306** [comment]
Hi, thanks for posting on github, the team will review the issue.
Similar issue mentioned on GitHub #[2412 ](https://github.com/CoinAlpha/hummingbot/issues/2412)
Where when running cross exchange market making or arbitrage using two different exchanges in paper trade only, and you run status, instead of showing two exchange, only one exchange will be displayed as both maker and taker. This affects the history output as well.

Tested on different build and version, issue persist: 
HB Version 0.32.0 docker build
![image](https://user-images.githubusercontent.com/12313129/95977838-8dd3d580-0e43-11eb-996b-e2ccb46a2d41.png)

HB Version dev-0.33.0
![image](https://user-images.githubusercontent.com/12313129/95979253-8f060200-0e45-11eb-8c1d-b3fe1521391d.png)

HB Version 0.32.0 Windows binary
![image](https://user-images.githubusercontent.com/12313129/95977383-0be3ac80-0e43-11eb-91cb-186bfe1d5897.png)

**Comment by dennisocana** [comment]
No response from user. Closing ticket for now, please feel free to reopen or reach out through our Discord server http://discord.hummingbot.io/ for further support.
