### ISSUE TITLE
Bybit Perpetual

### ISSUE THREAD

**Issue by pranaypratyush** [CoinAlpha/hummingbot#2509]
## Exchange Details ✏️

- **Name of exchange**: Bybit
- **Exchange URL**: https://www.bybit.com/
- **Link to API docs**: https://bybit-exchange.github.io/docs/inverse/#t-introduction
- **Type of exchange**: [*] Centralized [ ] Decentralized
- **Requester details**: Are you affiliated with the exchange? [ ] yes [*] no 
  - If yes, what is your role?

## Rationale / impact ✏️
(Describe your rationale for building this exchange connector, impact for hummingbot users/community)

Bybit's APIs are faster in my 'little' experience. I am actually surprised that no one has requested this yet as Bybit is pretty popular. It has -0.025% maker fees and doesn't require KYC so it's easy setup an account.

**Comment by TradeClaw** [comment]
I was wondering the same, especially now that they are expanding.
But their USDT contracts use dual websockets, which is a super weird design decision so that might not be the easiest thing to implement, no idea if Hummingbot can handle dual websocket setups.

It's also mainly focused on spot trading here.

**Comment by dennisocana** [comment]
Thanks for the suggestion. We're planning to integrate and include Bybit connector in this September's release (v0.43)

**Comment by dennisocana** [comment]
Already in staging branch. Target release date October 1st.
