### ISSUE TITLE
[BUG] Coinabse Pro API Key, Secret Key & Passphrase is not asked to setup a new configuration if already configured

### ISSUE THREAD

**Issue by sazed5055** [CoinAlpha/hummingbot#252]
**Describe the bug**
Coinabse Pro API Key, Secret Key & Passphrase is not asked to setup a new configuration if it's previously configured

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):

1. Install hummingbot and setup a new config
2. Set Coinbase Pro as taker with an invalid API Key/Secret Key
3. Restart the process by setting up a new configuration

**Expected Behavior**
API Key/Secret Key should be asked to enter again 

**Actual Behavior**
API Key/Secret Key are not asked to enter again therefore not possible to connect to Coinbase Pro anymore

**Screenshots**
![1](https://user-images.githubusercontent.com/50499987/57989770-2c54df00-7a76-11e9-88aa-3e3f02bec479.jpg)

**Release version**
0.6.0

**Comment by mifeng** [comment]
Since it's difficult for Hummingbot to discern for certain that the API key is invalid, we expect users to edit the config file to replace any invalid API keys. 

We will add something to https://docs.hummingbot.io/installation/api-keys/, but we won't make a change to code at this time to accommodate this issue.
