### ISSUE TITLE
[BUG] sell order spamming every second alltho insufficient balance

### ISSUE THREAD

**Issue by TradeClaw** [CoinAlpha/hummingbot#2611]
**Describe the bug**
Bot is trying to creating sell orders every second but insufficient balance.

**Steps To Reproduce**

Just a default setup as you can see in the config, only thing I changed to get rid off all my RLC was inventory pct to 0, so maybe that was the underlying trigger.
(reward payout threshold so high I will not make it anywhere soon)

**Screenshots**
![image](https://user-images.githubusercontent.com/63117227/98934433-5f98f280-24e2-11eb-9d88-3f8c2a9e9de2.png)

**Release version**
0.32.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
![image](https://user-images.githubusercontent.com/63117227/98934512-79d2d080-24e2-11eb-9ee5-96b4fea56593.png)

**Comment by RC-13** [comment]
This message occurs if the bot determines that you don't have enough balance to place an order using the current size you set (order_amount), Hummingbot keeps trying every second which is why the log pane is getting spammed. On version 0.33 our team introduce a feature to place order below the set order_amount. The order gets adjusted base on the current available balance you have  provided that it is still within the minimum allowable trade size of the exchange. If you're currently using version 0.32, we recommend updating to the latest version.
