### ISSUE TITLE
[BUG] Cosmetic bug in balance limit

### ISSUE THREAD

**Issue by glenntomas** [CoinAlpha/hummingbot#2647]
**Describe the bug**
// A clear and concise description of what the bug is.

* When setting balance limit to 0 it doesn't appear when you run `balance` command.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue:
1. Run `balance limit binance ETH 0` to set the limit to 0.
2. Run `balance` command to confirm the limit has been applied.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/73885708/99537393-94c3aa00-29e6-11eb-8223-c8ab70dd8330.PNG)

**Release version**
0.33.0

**Comment by PtrckM** [comment]
related to https://github.com/CoinAlpha/hummingbot/issues/2219

**Comment by dennisocana** [comment]
Updating this ticket to reflect the same behavior linked in the pull request.

- Setting the balance limit to zero will now show `0.0` value instead of the previous `-` to avoid confusion
- By doing this, it allows the user to not use any of the assets on a particular side. For example, setting balance limit USDT 0 and run BTC-USDT pair will initially create sell orders only then create both buy and sell when the initial order was filled

The PR also added a functionality to disable this limit by setting it to -1 e.g. `balance limit binance USDT -1`.
