### ISSUE TITLE
Reconcile Hummingbot trade history vs. exchange data history

### ISSUE THREAD

**Issue by carlolm** [CoinAlpha/hummingbot#2664]
**Feature Suggestion**

Periodically verify Hummingbot's trade history vs. exchange API data.

Currently, network connectivity issues result in missing trades or duplicate trades being recorded in Hummingbot's trade history.  This impacts the accuracy of `history`, `performance`, and all other features depended on historical trade data (kill switch, ping pong, hanging orders, etc).

**Impact**

Inaccurate historical trade data severely affects the use of the bot and the execution of strategies.

**Additional context**

Several users have reported issues related to this.

**Comment by mifeng** [comment]
Currently, I believe the client generally uses a WS subscription to the exchange's trades API endpoint in order to track trades. However, due to network connectivity issues, this may result in duplicate and/or missing trades.

Here's an approach for discussion. Note that this assumes that all trades in each tracked market are generated by the bot, which may not be the case:

1. Ensure that the current method records `tradeID` in local DB
2. Every [5] minutes, for each market pair tracked by the bot, call the "trades" REST API endpoint to fetch recent trades
3. Compare recent trades to those in local DB, using `tradeID`
4. De-dupe and fill in missing trades

## Notes
- Do this for Binance only for now, so that we can evaluate this approach and discuss how to apply to other connectors.

### Acceptance criteria
- Run a bot for 24 hours and check that afterwards, bot's record trades are same as exchange. Halfway through, stop WiFi for an hour.
- If bot is running `arbitrage`, bot record trades on multiple markets

**Comment by Nullably** [comment]
I'd like to suggest these acceptance criteria which makes them clearer and more exact on what to test/look for.
* Run any strategy (e.g. PMM), after some trades being filled, check the database see if the trades recorded matched.
* Run `history --verbose` to see if the trades are reported there correctly.
* Run the PMM, stop WiFi midway while maker order(s) still active on exchange, wait til the order is filled, connect the wifi back on, see if the bot recovers and records the trade correctly.
* Run the strategy for a long period of time, at least a day, see if trades are recorded correctly.
