### ISSUE TITLE
[BUG] amm_arb getting error "Market not ready" and "connector status: Unknown"

### ISSUE THREAD

**Issue by rapcmia** [CoinAlpha/hummingbot#2695]
**Describe the bug**
Dolm5415 had been running his bot over 16hours when he noticed that there was an error of "Market not ready" and "Connector status: UNKNOWN. This conenctor has one or more issues". Advise to relaunch the bot but getting the same error. User have noted that he have enough balance yet getting the error messages.

**Steps To Reproduce**
1. Setup AMM-Arbitrage
2. First connector set to Balancer WETH-USDC
3. Second connector set to Kucoin ETH-USDC
4. Start bot

**Screenshots**
![image](https://user-images.githubusercontent.com/73840223/101235879-42cd9480-3707-11eb-96e0-be100505e489.png)

**Release version**
v0.33.1

**Attachments**
[logs_conf_amm_arb_1.log](https://github.com/CoinAlpha/hummingbot/files/5646615/logs_conf_amm_arb_1.log)
[conf_amm_arb_1.txt](https://github.com/CoinAlpha/hummingbot/files/5646628/conf_amm_arb_1.txt)
![image](https://user-images.githubusercontent.com/73840223/101235969-f59df280-3707-11eb-9286-a6702948ac8b.png)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
dolm5415

**Comment by RC-13** [comment]
@rapcmia Kindly verify with the user if the same issue still persist. Also make sure that he has enough ETH balance to cover the transaction. If the same issue persist, it's possible that there might be a stuck transaction, you can suggest the following workaround:

Ask user to install [MyCrypto](https://mycrypto.com/account) and follow instructions to[ unstuck the transaction](https://support.mycrypto.com/how-to/sending/checking-or-replacing-a-transaction-after-it-has-been-sent#:~:text=Simply%20enter%20your%20transaction%20hash,mempool%22%20of%20our%20Ethereum%20nodes), after that he may try to test the strategy again.
 
Note: the `Unknown` status is normal since the protocol connectors are currently not on the connector_status dictionary and currently our engineering team are looking for a way to better handle Ethereum connectors. You can refer to Hummingbot [README.md](https://github.com/CoinAlpha/hummingbot/blob/master/README.md) for connectors status.

**Comment by rapcmia** [comment]
Sent follow up via Discord, waiting for user response.

**Comment by RC-13** [comment]
Closing issue since a Zendesk ticket is created to follow up with the user
