### ISSUE TITLE
Arbitrage profit margin bug

### ISSUE THREAD

**Issue by KirkBallou** [CoinAlpha/hummingbot#27]
Profit margin is way off if it is not matching pairs.

![image](https://user-images.githubusercontent.com/346184/55678585-fee71400-58c1-11e9-9e70-36455dafb53b.png)

**Comment by mifeng** [comment]
In the cross exchange and arbitrage strategies, you're crossing the base tokens (WETH to ETH) and quote tokens (BTC to DAI). WETH to ETH can be treated 1:1, but DAI to BTC clearly doesn't work. 

The bot's assumption there is that users only cross different stablecoins like DAI/USDT/USDC/TUSD. In that case, the stablecoin conversion module kicks in, which uses the CoinCap API price feed to determine the exchange rate between the stablecoins. Since you have BTC there, the bot is assuming a 0.981 exchange rate between BTC and DAI, which gives rise to the absurd Max Profitability % of 500,000%!

**Comment by martinkou** [comment]
Also, you need to have existing balance on both markets for the bot to generate trades.

e.g. let's say you want to arbitrage ETHUSDC and WETH-USDC, and their prices are 179.9 / 180.1 on ETHUSDC and 176 / 178 on WETH-USDC.

Then, the bot will buy WETH on WETH-USDC side and sell ETH on ETHUSDC side, with your existing balance on both exchanges.

**Comment by martinkou** [comment]
Closing this issue. Feel free to reopen if you have any further questions.
