### ISSUE TITLE
Cross exchange market making bugs

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#2769]
This story is a task to consolidate all bugs related to cross-exchange market making so we can discuss which outstanding issues we need to fix in this utility release to make the strategy more usable or solid as pure market making strategy.

Here are the following issues opened in Github:

https://github.com/CoinAlpha/hummingbot/issues/2754
https://github.com/CoinAlpha/hummingbot/issues/2629
https://github.com/CoinAlpha/hummingbot/issues/2310
https://github.com/CoinAlpha/hummingbot/issues/2125

@RC-13 we should also have the QA team do a lot of testing this week on this strategy, flush out as many bugs as we can that we can add to this.

**Comment by mifeng** [comment]
I agree with @dennisocana that QA should do a comprehensive review of the XEMM strategy. I took a look at the bugs above - some of these may be related to the connector not working, rather than the strategy, but #2629 may be a general problem with the strategy that we should fix.

Overall, I think QA should:
- focus on test XEMM with the largest centralized exchanges supported by Hummingbot (Binance, Huobi, OKEx, KuCoin, Kraken) in various combinations
- focus on testing the basic parameters and most commonly used advanced parameters (anti_hysteresis_duration, top_depth_tolerance)

**Comment by RobinR1** [comment]
I think 
#2412 
should be added to the list. It also seems to affect arbitrage hence it may be more of a paper mode bug, but it affects cross exchange too, making it impossible to test-drive cross exchange.

**Comment by RC-13** [comment]
@RobinR1 Thanks for the feedback, fix for that specific issue has been deployed on development branch (0.35.0) and will be out this coming release.
