### ISSUE TITLE
Allow `arbitrage` and `amm-arb` strategy to update the `conversion_rate` parameters from a external source/API

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#2797]
**Feature Suggestion**
Add a way for the bot to convert between fiat currencies.

**Impact**
A lot of arbitrage opportunities arrive between different an asset quoted on different fiat currencies, so allowing the bot to convert between different would open up more arbitrage opportunities.

Since the quote of local against each other also changes over time, I think the proper way to implement this is to allow the user to add an external API address for the bot to read the quote between these currencies.

**Additional context**

**Comment by phbrgnomo** [comment]
i noticed that the parameter `secondary_to_primary_base_quote_conversion_rate` actually fill that function.

But it is a constant value, so it would only work at the times where the local financial markets are closed (between 6 PM and 10 AM of the other day, in brazil's financial exchange, for example, but Forex markets are 24h, except weekends)

The problem actually would be to add a way to automatically update the current conversion rate, and change the above parameter.

**Comment by TheHolyRoger** [comment]
When I get a moment I'll have a look at what's needed and if I'm capable of making a PR as I need this too

**Comment by phbrgnomo** [comment]
Welcome back @TheHolyRoger. BTW, at first i thought about using an external API to check for fiat currency prices, but another quicker solution could be, use the current connectors exchanges API, since some of them, like Binance, already offer markets on additional fiat currencies. (for example, finance also have USDT(B)/BRL pairs.

This would also cover the cross-coins situations

**Comment by TheHolyRoger** [comment]
Tested and working here for me https://github.com/CoinAlpha/hummingbot/pull/2865 :)

**Comment by Nullably** [comment]
We used to have `ExchangeRateConversion` module in Hummingbot to get a rate of one token in another. Back in around April last year, we decided to decommission it due to a few problems with the module. Firstly, it relies on CoinGecko which wasn't very reliable back then, secondly there were many conflicts with token codes and names and also price feed was lagging in accuracy.

Though by removing the module, we also lost the ability to dynamically convert token values, hence Arbitrage and XEMM strategies now only allow for fixed rate conversion.

I think we should revisit the ExchangeRateConversion, though we can use a more reliable exchange like Binance for the price feed. I'll create ticket for this soon.

**Comment by phbrgnomo** [comment]
@Nullably We need a decision about what to do with the linked PR. Could you take a look at the state of this story before tomorrow's meeting?

**Comment by TheHolyRoger** [comment]
> @Nullably We need a decision about what to do with the linked PR. Could you take a look at the state of this story before tomorrow's meeting?

https://github.com/CoinAlpha/hummingbot/pull/3128

This PR ^ is the refactor one that needs to come first, and should come first @Nullably :) - it is just a **refactor and removal of duplicated code**

Regardless of whether the following 2 PRs actually want to be merged:

https://github.com/CoinAlpha/hummingbot/pull/2865
https://github.com/CoinAlpha/hummingbot/pull/3129
