### ISSUE TITLE
order_refresh_tolerance_percent not work if zero balance quote

### ISSUE THREAD

**Issue by tomma100** [CoinAlpha/hummingbot#2837]
**Describe the bug**

When no balance in in base order_refresh_tolerance does not force orders to cancel and move up with the price

**Steps To Reproduce**

start a bot with only quote currency and the following config 

![image](https://user-images.githubusercontent.com/19289703/104413586-7a312b80-5566-11eb-857e-04f00a8694d9.png)

although the screenshot does not catch it in the act, with those settings if the quote currency is 0 and the remaining order is over 0.2% then the orders do not refresh and replace closer to the ascending price.  They ought to be cancelled and replaced as the refresh rate is set to 1 second and order_refresh_tolerance_percent is set to 0.2

the problem is that if price continues to go up the orders sit an ever increasing distance away from the spread

**Release version**

0.34.0

**Attachments**

config file above

**Optional: your discord username:**

tomma100

**Comment by RC-13** [comment]
@tomma100 Base on the config and order spread, they haven't moved by 0.2% which is why your orders are not cancelled. With your configuration, orders will only be cancelled if spread moves and exceed 0.3% (0.1 +0.2)  or if the spread goes down to 0.008%. Here's a reference on how the order refresh tolerance work: https://docs.hummingbot.io/strategies/order-refresh-tolerance/#order_refresh_tolerance_pct

**Comment by cryptogasm** [comment]
Low liquid, even if you set 0.0 for your tolerance your bot will barely refresh, unless max order age reach.

**Comment by tomma100** [comment]
thanks - i will test that out and confirm

**Comment by RC-13** [comment]
Hi @tomma100 I just want to follow up, are we all set for this inquiry?

**Comment by RC-13** [comment]
Closing ticket
