### ISSUE TITLE
Percent for P&L Resets when program is closed or exits

### ISSUE THREAD

**Issue by rogueops** [CoinAlpha/hummingbot#2851]
**Describe the bug**
The percent for P&L resets to 0 so if you close and reopen or it crashes you start from 0 instead of what P&L you had last

**Steps To Reproduce**
Run the program so there is some P&L going and then stop the bot and then exit the program and then reopen program, should show 0% at the bottom even when the same configs and other settings are retained.

**Release version**
0.35

Optional: your discord username: n/a

Note: I am running the docker version, but I was running it on Windows 10 during testing and had the same issue, no retained history when the program is closed. It would be better to start where you left off instead of having to know to record the P&L before closing the program or you have no idea the actual P&L

**Comment by RC-13** [comment]
Hi, this is the current expected behavior for PnL and return% under the UI, once bot is closed or exited. However, you can use `history --days` to check your previous performance, or you can use `pnl --days` if you're trading on Binance. Note `pnl`  command currently supports binance only at the moment and you will need to configure your `conf_global.yml` file and add the market you're trading in under  `binance_markets`. For more information, you can check our documentation: https://docs.hummingbot.io/operation/command-ref/#commands-overview

**Comment by rogueops** [comment]
Great, thanks for the notes, you can close
