### ISSUE TITLE
Can't paper trade with terra when terra wallet empty

### ISSUE THREAD

**Issue by yasuiniko** [CoinAlpha/hummingbot#2902]
**Describe the bug**
I am following the tutorial listed here: https://hummingbot.io/blog/2021-01-terra-amm-arbitrage-trade/. When I `start` the sample configuration in paper trading mode, some initial startup steps are completed, but the markets are never ready. 

I don't know for sure but I think it's because I don't have anything deposited in the Terra blockchain. The only other thing that looked weird to me is that the Terra network status was yellow, but this youtube guide that CoinAlpha posted also had a yellow network status for Terra.

<img width="619" alt="Screen Shot 2021-01-31 at 15 20 08" src="https://user-images.githubusercontent.com/7184841/106399754-d05ff480-63d7-11eb-8e8f-f3284b030505.png">

**Steps To Reproduce**
Here are the steps to reproduce the issue (see config, etc in the section below):
1. Follow tutorial to create `amm_arb` strategy.
2. Add to paper trade balances: 1000 LUNA, 500 UST, and 500 USDT.
3. Enable paper trading mode.
4. Start the bot using this command: `start`

**Screenshots**
<img width="325" alt="Screen Shot 2021-01-31 at 15 24 56" src="https://user-images.githubusercontent.com/7184841/106399876-7c094480-63d8-11eb-9630-d9710066e816.png">
<img width="173" alt="Screen Shot 2021-01-31 at 15 25 14" src="https://user-images.githubusercontent.com/7184841/106399884-862b4300-63d8-11eb-9346-4a1a89f13a61.png">

**Release version**
Mac Docker 0.35.0

**Attachments**
From config folder:
[attempt2.yml.txt](https://github.com/CoinAlpha/hummingbot/files/5900855/attempt2.yml.txt)
[conf_global.yml.txt](https://github.com/CoinAlpha/hummingbot/files/5900856/conf_global.yml.txt)
[hummingbot_logs.yml.txt](https://github.com/CoinAlpha/hummingbot/files/5900857/hummingbot_logs.yml.txt)

From log folder:
[logs_attempt2.log](https://github.com/CoinAlpha/hummingbot/files/5900837/logs_attempt2.log)
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/5900840/logs_hummingbot.log)

**Comment by RC-13** [comment]
Hi @yasuiniko, the current connector status/ color code for Terra means that either it has one or two reported github issues or it's a new connector. For this case, Terra is a new connector which is why we tagged it as Yellow. 

Regarding to your concern, you need to check if you have installed or if your gateway instance is running, On the blog post and video, the gateway-instance installation was skipped since we have the step on our [quickstart for amm-arb](https://hummingbot.io/academy/amm-arb/) guide, if you don't have gateway yet, kindly follow the step on our quickstart guide. 

As for the `paper_trade` option, I just want to let you know that this is for non-protocol connector such as Binance, KuCoin, Kraken, and etc. Although it would still work, for testing purposes, you can setup your gateway instance to use Terra testnet ( Kovan for Balancer and Uniswap)
![image](https://user-images.githubusercontent.com/57189990/106408037-7f540d00-6478-11eb-9034-370e13e81a05.png)
and also you need to get some [testnet asset](https://faucet.terra.money/) for your Terra account . If your instance and asset are all set, retry running your strategy. In case you need additional support, we highly recommend chatting with us on our discord channel so we can assist you real time.

**Comment by yasuiniko** [comment]
Thanks, will do.
