### ISSUE TITLE
Question on Ubuntu Version

### ISSUE THREAD

**Issue by rogueops** [CoinAlpha/hummingbot#2903]
I have my bots running on a server, it's Ubuntu 20.04 which does not show it is supported, but is working just fine as far as I can tell. On my VPS host for Ubuntu, I do not get the option for 19.X, only 18.X, and then 20.X and 21.X. Are there any issues running it on 20.04? Would it run better on 18.04? I use docker to run multiple so I wanted to ask as I can redo do it to a supported Ubuntu version in 5min if it will run better.

**Comment by rogueops** [comment]
Will hummingbot run on Debian with docker?

**Comment by rapcmia** [comment]
I'm curious so I tried 20.4 as well and it worked ok with docker :) However, the current versions 16.04 LTS, 18.04 LTS, 19.04 are tested and should be able to run without issues. I'd suggest to use 18.04 since this is the one I'm currently using with docker. 

We would need to look if using Ubuntu 20.4 will be a added as an option. For now, we'd like to suggest to use the supported versions.

Link:
https://docs.hummingbot.io/installation/linux/#ubuntu

**Comment by rogueops** [comment]
glad I asked, ill switch, appreciate the response, closing ticket
