### ISSUE TITLE
Aggregate Data Collection: Allow user to set levels of detail

### ISSUE THREAD

**Issue by jason-hb** [CoinAlpha/hummingbot#2914]
**Feature Suggestion**
Several hedge funds and market makers that I've spoken with have disabled the Aggregate Data Collection setting. When I asked why the answers all came back to not wanted to share the pairs they are trading (even though I reassured them Hummingbot is not sharing/reselling the data). Several said they would be willing to re-enable the feature if it was possible report ONLY trade volume. Since this is the most important metric needed, I propose we add a way for users to choose their level of reporting.

Existing data collected would be called: Standard
New limited data collection would be called: Volume Only

**Impact**
Allows Hummingbot to accurately measure more of the volume coming through the client...particularly the volume from larger users

**Comment by jason-hb** [comment]
Paulo & Dennis,

Let's discuss this on Thursday. Mike and I talked about it a couple of weeks ago and I think we decided just to reduce all data collection to just the exchange & volume (denominated in USD). Spoke to Jack about it also and the conversion to USD at time of  collection is the only tricky part.

Regardless, this needs to be in v0.39.

Jason

**Comment by phbrgnomo** [comment]
@mifeng comments from #2841:
Why
Since trade volume is denominated in quote token, it's hard to get a complete picture of daily fill volume coming from Hummingbot clients

What
Use the USD conversion that @Nullably added to balance command to convert record trade volumes to USD, and add to data reporting.

Acceptance
Run bots on different connectors for 48 hours and confirm that USD fill volume is correctly calculated in Datadog

**Comment by dennisocana** [comment]
Completed in version 0.39 release.
