### ISSUE TITLE
Stoping the bot with hanging orders have problems cancelling the open orders

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#2955]
**Describe the bug**
When using hanging orders after a long time, when hitting the `stop` command the bot have problems canceling the current open orders and I have to type `stop` repeatedly until the bot recognize the orders were actually cancelled.

After entering `stop` the hanging orders are canceled, but the bot doesn't recognize it.

On this situation, the bot stays "locked", and not connected to the exchange. enterting `start` doesn't connect with the bot again.

Only solution is entergin `exit -f`, but when the bot is restarted, the orders that should have been canceled with the `stop` or `exit` are recreated.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
![Captura de tela 2021-02-15 11 28 20](https://user-images.githubusercontent.com/34484531/107958635-0e851880-6f81-11eb-8f2a-6c7f0fb0c844.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by RC-13** [comment]
Similar case:  #2890, the only difference is that it can be easily triggered by network interruption on Okex:

**Comment by phbrgnomo** [comment]
Possible solution: Add an extra parameter to `stop` and `exit` that will clean up the hanging orders registered on the bot, so when a `start` happens again, the strategy would start as if it were the first time.

**Comment by Nullably** [comment]
@phbrgnomo 
This issue is quite difficult to reproduce. The hanging orders logic is quite complicated.
At how many hanging orders approximately do you encounter this issue?
Can you please attach your strategy config file and log file?

My estimate to fix this issue is probably somewhere between 1-4 days.

**Comment by Nullably** [comment]
> Possible solution: Add an extra parameter to `stop` and `exit` that will clean up the hanging orders registered on the bot, so when a `start` happens again, the strategy would start as if it were the first time.

It's probably better to have this as a new command, so that a user can use it without having to first `start`, or having to `exit`. The command will simply delete all in-flight and stale orders from the sqlite db. 

This is quite simple to accomplish, about a day worth of work.

**Comment by aarmoa** [comment]
@phbrgnomo do you have the details of how much time you waited in between executing the stop command and trying to start the strategy again?
According to your first screenshot there are 28 orders to cancel when the when the bot is stopped. Since the cancellations are executed one by one, and each request to the server will consume some API credits, in this case it is sure that the throttle component had to delay some requests. 
Are you expecting the bot to be ready to start right away after stopping?

**Comment by aarmoa** [comment]
> Possible solution: Add an extra parameter to `stop` and `exit` that will clean up the hanging orders registered on the bot, so when a `start` happens again, the strategy would start as if it were the first time.

That could be a problem in some scenarios. Imagine the case of a bot that is running with 30 active orders. Imagine that we stop the bot, and since it takes time to cancel all active orders, we force the exit (exit -f). There will be many orders that are still alive in the exchange, since the bot could not send the cancel request for them. If you reset all previous status before restarting the strategy, the bot will not be able to track the orders from the previous session, and those orders will still be alive in the exchange. They could end up being filled in any moment.
Maybe it would be better to have a special command like @Nullably mentioned before, but that command should not only remove the inflight and stale orders. It should also make sure to send a cancel request to the exchange for each of them.
