### ISSUE TITLE
Beaxy - False trade notification in client

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#2990]
**Describe the bug**
- bot shows that there is filled orders but non on bot history and exchange itself.

**Steps To Reproduce**
- create PureMM strategy
- select beaxy as exchange connector
- set your token pair, tight spreads and order amount
- start the bot
- after few minutes you get bunch of filled orders

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/109155591-b46b2b00-77aa-11eb-8dda-bf2bf6fd5db3.png)
![image](https://user-images.githubusercontent.com/54516858/109153936-8d135e80-77a8-11eb-8fe5-f4adb81702a9.png)
![image](https://user-images.githubusercontent.com/54516858/109153880-766d0780-77a8-11eb-8bc5-40999201a002.png)

**Release version**
https://github.com/CoinAlpha/hummingbot/pull/2913

**Attachments**
[logs_ping_pong.log](https://github.com/CoinAlpha/hummingbot/files/6042936/logs_ping_pong.log)
[ping_pong_sqlite.log](https://github.com/CoinAlpha/hummingbot/files/6042948/ping_pong_sqlite.log)

**Comment by novoxd** [comment]
Want to add info from the maintainer side. Currently, this bug is under investigation. The mechanism of the bug is not fully known. Currently, it seems that:

1) bot places the order
2) bot cancels the order
3) the order was successfully canceled from the backend side, order removes from tracking by the bot
4) somehow Beaxy backend sends `complitly_field` msg in the `user_stream`, while it seems that order is closed on the backend side
5) internal processing triggers the `*_ORDER_COMPLETED_EVENT_TAG`
6) what prints the "order filled" message

**Comment by novoxd** [comment]
Should be fixed by https://github.com/CoinAlpha/hummingbot/pull/2913/commits/9d61893ae064de0b458d079ed9db437a6a7ae645

**Comment by RC-13** [comment]
Closing ticket, the issue did not re-occur.
