### ISSUE TITLE
How to change c_tick interval ?  

### ISSUE THREAD

**Issue by Amenocy** [CoinAlpha/hummingbot#3019]
Hi
I want to change the 1-sec interval of c_tick, how can I do that?

**Comment by sidmontanez** [comment]
Hi Amenocy! If you're a developer and familiar on tinkering the code base, I believe you can change the tick value but it's more suited to ask this on our #dev-general channel from our discord if you plan to do so. You could modify the value from this code base `tick_size: float = [value]` since normally it's set to 1 second every tick.

![tick](https://user-images.githubusercontent.com/78310937/110205374-896f8e00-7eb2-11eb-943b-f8d2d58cf765.jpeg)

You can also look into visiting our documents on building a strategy to help you with your concern. Here's a link that you can follow: https://docs.hummingbot.io/developer/build-strategy/#add-time-delay-between-trades
