### ISSUE TITLE
Discussion on fetching trading pairs for all connectors at start of bot

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#3045]
Currently when we start Hummingbot we fetch all trading pairs from all the connectors. We discussed about the possibility of one of the exchanges is down and not returning the list of trading pairs that resulted to this P0 bug https://github.com/CoinAlpha/hummingbot/issues/3042

The solution we agreed is to implement a timeout so it doesn't keep sending an API call when it can't fetch the trading pairs.

While adding a timeout is a quick fix, we should figure out an approach like instead of pulling all trading pairs at the start of Hummingbot for every connector we could just pull the exchange API after the user enters the exchange into the strategy.

Created this story for discussion.

**Comment by phbrgnomo** [comment]
Ideas for discussion from Discord:

what about pre-load, save on a local file (so the bot uses the local information), then on the background if there is any changes. if so, the update happens
or use the local file, but having a command update_pairs or something. with it, the bot check if there is any changes, ask if user want to update, and warns that it might take some time
something similar to sudo apt update then sudo apt full-upgrade

**Comment by Nullably** [comment]
In an async API request operation, the number of concurrent requests doesn't matter (unless we go over 1000 or so but that's another story). Whether we fetch trading pairs from 5 or 100 exchanges, the slowest request will determine the time for the fetch to complete not the number of requests. 

The problem with #3042 is we have synchronous calls (`requests.get`) mixed within the async calls, those calls increase the fetch time significantly. The fetch time is now the slowest async call plus the fetch time for each of the sync call. The sync calls also blocks UI thread hence the UI appeared frozen.

Another problem is we didn't use `timeout` on both async and sync calls, hence the slowest request still affects the fetch time significantly.

The solution I'd to propose is:
- Ensure we don't use synchronous `requests` calls (to be replace with `aiohttp`). The exception is `python-binance` library where we wrapped up the sync calls properly. 
- Ensure we use `timeout` or `wait_for` for all async API calls, the default timeout is 5 minutes, this may be too long. https://docs.aiohttp.org/en/stable/client_quickstart.html
- Ensure we handle exceptions in case the fetch calls failed like what @keithbaum did on https://github.com/CoinAlpha/hummingbot/pull/3059   
- This should apply to other area where we do REST API calls not just the fetch trading pairs.

**Comment by Nullably** [comment]
My opinion on some suggestions above

>>> Fetching the pairs after the user puts in `exchange`

The market config is always right after the `exchange` input, this is probably not enough time for the API request to complete and thus the user won't see auto complete suggestion. Since the configuration is on the sync operation, there is no easy way to start and to wait for the async request. This is probably the main reason we fetch trading pairs as soon as the bot starts.

>>> Saving trading pairs on local 

This is doable, it's just gonna be a significant amount of work. There is no easy way to check if the list is out of date and the user will have to manually update the list. The main use of trading pair fetcher is to have an auto complete suggestion and input validation, they are nice to have kinda feature but they are not needed for the bot to run. I don't think we should implement the whole system of record keeping and updates for it.

**Comment by keithbaum** [comment]
Also something discussed with @phbrgnomo was besides having 100% async calls, to allow the requests a generous timeout but with a progress bar or something dynamic in the ui so user sees there’s activity in the background.

**Comment by Nullably** [comment]
2-3 seconds for API request is already very generous. If you want to estimate a maximum allowable time, it is the time between a user login and when they first need to put in a trading pair.

Another thing I want to point out is since before the sync API call was introduced (v0.36), we didn't have problem with this trading pair fetcher, it worked just fine, it's all happening in the background.

**Comment by phbrgnomo** [comment]
A big issue for me is that there is no informations about what is going on. I think that, no matter what the final solution is, some kind of information about the loading/problem with the fetcher must be better shown on the client interface.

**Comment by Nullably** [comment]
We can log messages in the case where the fetcher fails on certain API, this will show up on the right hand side of the screen.
I don't think we need a specific progress bar to show the progress.

**Comment by Nullably** [comment]
I believe this issue is addressed in the below PRs
* #3067
* #3071
* #2905 

They are all ready for testing and code review.
