### ISSUE TITLE
Question: Buying high / Selling low. Pure market making

### ISSUE THREAD

**Issue by Corfucinas** [CoinAlpha/hummingbot#3184]
I might have misread something during the initial configuration. 

```
2021-04-07 06:19:32 buy 2096.3 0.00620 
2021-04-07 07:08:03 sell 2074.9 0.00620
```

Is there any particular reason why the bot would sell at a loss using Ping Poing and Hanging orders? If the price has moved opposite of the entry of a `Ping`, shouldn't the `Pong` remain at a distance to the `profit` and not the price? (ie, ignore the price, leave the order there until it is matched at a profit). 

Market-making is mainly a neutral strategy, the `Pong` should not go under profitability following the `Ping` below entry price.

**Comment by glenntomas** [comment]
Hi! I think because the market moves constantly. But there are parameters you might want to look at. You can try it first in `paper_trade` mode and see what works on your strategy.
- `price_type` then choose `mid_price`, `last_price`, `last_own_trade_price`, `best_bid`, `best_ask`, and `inventory_cost`. (https://docs.hummingbot.io/strategies/external-price-source/#price_type)
- `minimum_spread` this parameter allows Hummingbot to cancel the active order right away when its spread dips below the specified value. (https://docs.hummingbot.io/strategies/minimum-spread/)
- `price_band` parameter what it does is you can set `price_ceiling` to place only sell orders when mid price goes above this price and set `price_floor` to place only buy orders when mid price falls below this price.
(https://docs.hummingbot.io/strategies/price-band/)

We have 24/7 online support on [discord](https://discord.com/invite/2MN3UWg) feel free to leave a message and chat with one of our support.

**Comment by RC-13** [comment]
Hi, @Corfucinas just to verify, for the sell order that was filled, is that the hanging order or the sell order that was created on the next order cycle (when ping-pong is activated)? The hanging order shouldn't change its price even if the price move in the opposite direction. However, the newly created order (order after the first cycle) will be affected by the change in price since the bot will re-calculate and may set a lower price.

**Comment by Corfucinas** [comment]
@glenntomas 

Yes, correct, Ping Pong should only create an opposite order. 

For example:

Wallet: 0 eth / 100 USD

Eth price : $100

Bid spread 1%
Buy (ping) - $99

Now an order will be created since the wallet holds funds

Ask spread 2%
Sell limit order created (pong) - $102

If the price in this scenario goes down to $80 (a 20% correction), the Pong order for the Ping  at $99 needs to remain at $102

@RC-13  bases on your observation, then it's better to disable the order cycles?

**Comment by RC-13** [comment]
@Corfucinas You won't be able to disable the order cycle but you can adjust your order refresh time and filled delay time if you want your orders to stay longer in the order book. 

For the given example above, if hanging order is enabled and your bot places 2 orders at the same time (bid at 99 and ask at 102) and the buy order gets filled then your sell order becomes hanging order (price will remain at 102). On the next order cycle, this is where ping-pong gets activated. It will remove the new buy order and create a new sell order. If the price drops during that period then only your new sell order is affected (assuming the selling price is at 80). At this point, you will have 2 sell orders (a hanging order at 102 and the sell order at 80). If the non-hanging sell order gets filled first then the chance is you will see buy high and sell low under history, however, if the hanging order gets filled first then you should have a profit.

**Comment by Corfucinas** [comment]
@RC-13 

Is there's a way to disable that "sell order at 80". Why would I want to have a sell order at 80 if I bought an order at the big of 99? If the price moves against me, I wish to only leave the order open at a profit.

**Comment by RC-13** [comment]
@Corfucinas There's no way to disable that since in pure market making, you constantly create and cancel your orders. However, this is where another parameter comes in to aid you, such as configuring your order refresh time, hanging order, filled order delay, etc. You can check this blog: https://hummingbot.io/blog/2020-10-inventory-risk/ It might give you more insight on how you can configure your strategy.

**Comment by Corfucinas** [comment]
@RC-13 

Thanks, I'll tinker with the strategy after digesting the guides once again

**Comment by RC-13** [comment]
I'll be closing this ticket, feel free to reach us again thru our [discord server](https://discord.hummingbot.io/) if you have an additional inquiry.
