### ISSUE TITLE
Perpetual Market Making + Profit Taking

### ISSUE THREAD

**Issue by BanditsAtZero** [CoinAlpha/hummingbot#3192]
Dear,

I hope you can help me with this, and I'll do my best explaining the problem to you.

I wrote a simple bot, but it doesn't execute orders as I expected.
This is the config. It's very basic, it places orders 0.1 away from mid_price.
Both bid_spread and ask_spread are equal at 0.1
![image](https://user-images.githubusercontent.com/82179949/114089477-7cc9c580-98b6-11eb-95ca-f2e55f3270ec.png)

The problem I am experiencing is. **I need the bot to buy (bid_spread) and sell (ask_spread) orders in the opposite direction.**

Example of the bot placing orders at the moment.
![image](https://user-images.githubusercontent.com/82179949/114092372-19da2d80-98ba-11eb-8ef8-77675acf5653.png)
First line the price is HIGHER than mid_price, bot places Sell order (should be Buy order).
Second line the price is LOWER than mid_price, bot places Buy order (should be Sell order).

If you put this in the chart, it would look something like this.
![image](https://user-images.githubusercontent.com/82179949/114093426-62461b00-98bb-11eb-9978-59bbe1df2ae6.png)
This means if a position is filled for my Sell order and the chart keeps going UP I lose money and eventually liquidated.

My strategy is placing quick orders and filling the position when the chart goes in that direction. Picking up small profits.
If the chart goes UP place a Buy/Long order, when the chart goes DOWN place a Sell/Short order.

I sincerely hope this is something you can help me with. I'm struggling to use your bot because of this problem. In my eyes how the bot works now it has no advantage.

Regards,
Sven

**Comment by dennisocana** [comment]
@BanditsAtZero thanks for explaining your situation very thoroughly. Allow me to explain further how the perpetual market making strategy works by dividing its behavior into three main parts:

1. Creating limit orders to OPEN a position
2. Opening positions based after a filled order event
3. Creating limit/market orders to CLOSE a position

Like pure market making strategy, the bot will create a limit buy and sell order with prices based on `bid_spread` and `ask_spread` settings. Spreads are how far away your orders are from the mid price. For example, if the mid price is $10,000 while your bid and ask spread is 1% then your orders will be:

Sell order = $10,100
Buy order = $9,900

The bot waits which order gets filled first. Since you're using `Profit_taking` for position mode, it will cancel the opposite order, open a position and create a new profit taking order.

Using your screenshots and configs as an example, let's your buy order priced at 57,696.10 was filled. The bot should cancel the sell order priced at 57,811.61, open a LONG position, and create a profit taking sell order 0.1% away from your entry price (based on `long_profit_taking_spread` value).

Entry price = 57,696.10
Profit taking sell price = 57,753.79

We have a pending change to improve the perpetual market making strategy documentation that we will publish today.

**Comment by BanditsAtZero** [comment]
@dennisocana Thank you for taking the time to reply.

> Using your screenshots and configs as an example, let's your buy order priced at 57,696.10 was filled. The bot should cancel the sell order priced at 57,811.61, open a LONG position, and create a profit taking sell order 0.1% away from your entry price (based on `long_profit_taking_spread` value).

Let's go further on this example.
So first of it does not cancel the sell order. This one stays open for some reason.
Second, why would the bot make a long order when the price goes down? That makes no sense to me....
I just want the bot to create a LONG order on a price that is higher than mid_price and a SHORT order when the price is lower than mid_price.
This makes the most sense to me.

> We have a pending change to improve the perpetual market making strategy documentation that we will publish today.

Looking forward to it.

**Comment by rapcmia** [comment]
Can you please share a log file of your bot so we can have a look into it? 
Perpetual Market making is designed to OPEN a position based on which limit orders will be filled first and from there it will create a take profit order so when it is filled it will CLOSE the position. 
Here is the updated docs for our Perpetual Market making: https://docs.hummingbot.io/strategies/perpetual-market-making/

**Comment by rapcmia** [comment]
Hi, @BanditsAtZero good day to you,
Just checking this ticket again with you again and assumed that you have visited our updated docs for Perpeptual Market_Making strategy. We will be tagging this as solved now and you can reopen or contact our support in [discord](https://discord.com/invite/2MN3UWg) for another issue. Thank you

**Comment by RC-13** [comment]
Closing ticket for now
