### ISSUE TITLE
Unit tests for strategy base and common strategy classes

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#3272]

**Comment by Nullably** [comment]
- hummingbot/strategy/market_trading_pair_tuple.py
- hummingbot/strategy/order_tracker.pyx
- hummingbot/strategy/strategy_base.pyx
- hummingbot/strategy/strategy_py_base.pyx

**Comment by CrimsonJacket** [comment]
1. MarketTradingPairTuple **[Done]**
   - Noticed that some `PriceType` isnt being handled. i.e. `LastOwnTrade` and `InventoryCost`
   - Considering this this is essentially a wrapper class, I've chosen to just include the expected behaviour tests.


2. OrderTracker **[WIP]**
   - The unit tests for this will be slightly complicated, considering I will need to write up `@staticmethod`s to simulate certain strategy actions. i.e. Place Order, Cancel Order, Order Complete

3. StrategyBase **[Pending]**

4. StrategyPyBase **[Pending]**

**Comment by CrimsonJacket** [comment]
@Nullably, @phbrgnomo, @aarmoa, @james-hummingbot 

Some observations I have while working on the Unit tests for OrderTracker, is that it still includes functions to track `OrderType.MARKET` orders. We have since deprecate placing of `MARKET` orders. Was wondering if I should ignore these functions(i.e. `c_start_tracking_market_order`)
