### ISSUE TITLE
Spot Perpetual Arbitrage Bot continuously open new trades

### ISSUE THREAD

**Issue by onegoodtrade** [CoinAlpha/hummingbot#3341]
**Describe the bug**

I am running a spot perpetual arbitrage bot on binance, worked well for a few days, but on 2021-05-09, it started to buy-sell repeatedly for about 15 times within one minute, eventually settled down but caused large commission charges. If it didn't stop it could drain all my accounts!

looking at the log file, it seems the bot will continue to open new trade if Current spread < minimum convergence spread, only stop when Current spread > minimum convergence spread. The correct logic should be that when  Current spread < minimum convergence spread bot should only close existing position, not open new position.

**Steps To Reproduce**

I think setting minimum convergence spread close to Current spread will  reproduce the issue 

**Release version**

0.38.1

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

![image](https://user-images.githubusercontent.com/74208107/117629985-a191b100-b172-11eb-87bc-d97597cce4cb.png)

[logs_conf_spot_perpetual_arbitrage_1.log](https://github.com/CoinAlpha/hummingbot/files/6450615/logs_conf_spot_perpetual_arbitrage_1.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
jet2

**Comment by krisj** [comment]
I can confirm that this also happens with Perpetual Market Making strategy. The behaviour is similar to what you are describing - when opening the 1st order for the position (in hedge mode) on some rare occasion it goes into placing at least 8 or so orders at rapid fire rate (about 7-15 orders added into position within the space of 5-15 seconds or so) which does not seems to be helped in any way by filled_order_delay or order_refresh_rate for example (this test bot config had those rates at 60 seconds or more). Had a small test account liquidated due to this. It could be due to network/Binance API  issues and Hummingbot unable to correctly assess the open position existence and/or size.

Very dangerous indeed. I would recommend people not use any Perpetual strategy until this is fixed. Only started happening around 0.37 / 0.38 but maybe it is not relevant to the version.

I was hoping to gather more evidence to post a separate issue but it seems you have enough already here. I am just adding that this exact behaviour also happens on non-arb Perpetual Market Making strategy.

**Comment by zappra** [comment]
@krisj are you able to share a config for perpetual market making?

**Comment by krisj** [comment]
@zappra will try to find time later today yes

**Comment by naghdy** [comment]
+1 I just experienced this bug. Let me know if you want me to share my logs as well.

**Comment by naghdy** [comment]
Let me know if the attached works. There is also a chance that I set it all up wrong...
[RLC-SPOT-PERP-ARB-V2.zip](https://github.com/CoinAlpha/hummingbot/files/6453945/RLC-SPOT-PERP-ARB-V2.zip)

[trades_RLC-SPOT-PERP-ARB-V2.csv](https://github.com/CoinAlpha/hummingbot/files/6453942/trades_RLC-SPOT-PERP-ARB-V2.csv)
[logs_RLC-SPOT-PERP-ARB-V2.log](https://github.com/CoinAlpha/hummingbot/files/6453944/logs_RLC-SPOT-PERP-ARB-V2.log)

**Comment by onegoodtrade** [comment]
> Let me know if the attached works. There is also a chance that I set it all up wrong...
> [RLC-SPOT-PERP-ARB-V2.zip](https://github.com/CoinAlpha/hummingbot/files/6453945/RLC-SPOT-PERP-ARB-V2.zip)
> 
> [trades_RLC-SPOT-PERP-ARB-V2.csv](https://github.com/CoinAlpha/hummingbot/files/6453942/trades_RLC-SPOT-PERP-ARB-V2.csv)
> [logs_RLC-SPOT-PERP-ARB-V2.log](https://github.com/CoinAlpha/hummingbot/files/6453944/logs_RLC-SPOT-PERP-ARB-V2.log)

I had a look at your log file, here is what I observe:
there is only one [first arbitrage] message: "INFO - Spread wide enough to execute first arbitrage!: " at 2021-05-10 16:42:13,976
after that many many messages for the [second arbitrage]: "INFO - Spread low enough to execute second arbitrage!"

So the bot clearly should not initiate second arbitrage trades without checking if there is prior first arbitrage

**Comment by naghdy** [comment]
Just confirming if you are logging that info or if it's something I'm doing
wrong?

**Comment by onegoodtrade** [comment]
I don't think you did anything wrong. the bot has a very fatal bug, should not be used at current state.

**Comment by naghdy** [comment]
Ack makes sense. Good luck!

**Comment by rxlxrxsx** [comment]
Confirming the bug as well. See attached log/config file:

[spot_perp_bug.zip](https://github.com/CoinAlpha/hummingbot/files/6462622/spot_perp_bug.zip)

**Comment by zappra** [comment]
Any more repros in perpetual market making?

**Comment by dennisocana** [comment]
Fix available in tomorrow's version 0.39 release
