### ISSUE TITLE
Failed Test PR #330 - Getting insufficient balance error message

### ISSUE THREAD

**Issue by mrhzysbl** [CoinAlpha/hummingbot#337]
## Summary and Screenshots
Getting insufficient balance error when the bot is trying to cancel the orders. After the cancellation, it will prompt a message regarding insufficient balance and then only 1 order will be created on the next refresh. 

https://user-images.githubusercontent.com/120451804/230330453-f5965823-5af5-4a7f-ad4c-404360c335a2.mov

``` ruby
2023-04-06 14:28:45,111 - 3091545 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Insufficient balance: SELL order (price: 5.349000, size: 2.000) is omitted. 
```

## Steps To Reproduce
1. Clone and install feat branch
2. Connect to gateway
3. Create a perpetual market making strategy
4. Start the bot
5. Run status --live command and obseve the placing and cancellation of orders

## Expected Results

The orders will be cancelled without any errors.

## Test Result Comparison
n/a

## Attachments
[Inj_balance.zip](https://github.com/CoinAlpha/armada/files/11170204/Inj_balance.zip)

Another QA tried to replicate the issue and is also getting the same error. Here's the file.
[Injective_perp.zip](https://github.com/CoinAlpha/armada/files/11168370/Injective_perp.zip)

**Comment by petioptrv** [comment]
If you take a look at the available balance at the moment this message shows up, it *is* the case that you'd have sufficient balance to place the buy order but then you won't have enough to place the sell order. Once the first order gets successfully canceled, you stop receiving that message because the available balance is now sufficient for both orders. The real issue here is the fact that the second order failed to cancel, but debug logging is not enabled for that log, so I don't have the extra information to try to diagnose it.

**Comment by mrhzysbl** [comment]
No issues longer found when creating orders/balance updates
