### ISSUE TITLE
Liquidity Mining Strategy - "Error fetching [exchange] market snapshot" for pairs that are not available in the exchange.

### ISSUE THREAD

**Issue by sidmontanez** [CoinAlpha/hummingbot#3384]
**Describe the bug**
`liquidity_mining` strategy throws out an error :  `hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Error fetching Kraken market snapshot for ETH-BCH. Error is ['EQuery:Unknown asset pair'].`

Invalid pair is being accepted by the trading pair validation during the configuration. 

**Steps To Reproduce**

1. Create a `liquidity_mining` strategy
2. Select Kraken as the `exchange`
3. Run a pair that's not available on the exchange for example `ETH-BCH` 
4. Start the strategy and the error will show 

**Screenshots**
// If applicable, add screenshots to help explain your problem.
-
![image](https://user-images.githubusercontent.com/78310937/118533577-cdb4bf80-b77a-11eb-9fe2-ffd396f31341.png)

-ETH-BCH Pair is unavailable from Kraken
![image](https://user-images.githubusercontent.com/78310937/118533979-4fa4e880-b77b-11eb-872a-859e02f4b2ba.png)

**Release version**
Version: 0.38.1

**Attachments**
[logs_krakenlmtest.log](https://github.com/CoinAlpha/hummingbot/files/6495784/logs_krakenlmtest.log)

**Comment by RC-13** [comment]
@sidmontanez We currently don't have market pair validation for liquidity mining strategy which is why it was accepted during strategy setup but filtered by the bot resulting in getting the error. The correct format for that pair should be BCH-ETH
![image](https://user-images.githubusercontent.com/57189990/120125266-a1715800-c1ea-11eb-8188-c62b34ccaac0.png)
Note, that market validation would be added once the miner API becomes available.

**Comment by RC-13** [comment]
Closing this ticket for now.
