### ISSUE TITLE
Investigate Hanging orders sync problems

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#3414]
**Description**
As related to bugs #2955 and #3374, when `hanging_orders` is used on current `pure_market_making` strategies, hummingbot client shows some problems when trying to sync local order information with exchange-side order information, leading to orders being not being properly tracked.

This problem seems to intensify the longer the bot runs, and there is a lot of orders needed to be tracked and synced.

**Requirements**
Investigate what could be the root cause of this issue and propose possible solutions.

**Comment by aarmoa** [comment]
Findings:

- At the moment of doing the startup, besides restoring the market state (self.markets_recorder.restore_market_states(config_path, market)) we could also run a refresh of orders from the DB, and include as inflight orders those that were not part of the market state and are still alive in the exchange (suggestion to tackle issue https://github.com/CoinAlpha/hummingbot/issues/3374)

- The method restore_tracking_states(saved_states) in all ConnectorBase subclasses (ie: for all exchanges) should be implemented to include an order in the inflight list only if the order was still alive according to the market state stored in the database. Some connectors already validate the orders before adding them back, but others don't.
Example of exchange requiring this enhancement: Binance

- The method HummingbotApplication>>_cancel_outstanding_orders() should be improved to only cancel orders with any of the possible active statuses. Any order that has already been filled, cancelled, has expired or has been rejected (ie: it is not active) should not be included in the list of orders to cancel. The logic is really in the cancel_all(timeout) in every connector. In several implementations the logic already takes current status into account. That should be extracted and used in all connectors.

- For the connectors that implement _update_order_status() we might change the logic when a response from the exchange was received for a particular order, but the order is no longer an inflight order.
Currently if the order is not in the inflight list, the response from the exchange is ignored. But I think we should take care of the scenario where we receive a response from the exchange and the order is no longer in the inflight list. If that is the case we might need to request a cancelation to the exchange (it might not be possible to recreate the order and insert it back into the inflight list because we don’t have the required information to recreate the order object in the response from all the exchanges)

**Comment by aarmoa** [comment]
For point 1: https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/coinalpha/hummingbot/3454
Point 2 has been disregarded by Jack
Point 3 was categorized as low priority by Jack: https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/coinalpha/hummingbot/3456
For point 4: https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/coinalpha/hummingbot/3455

**Comment by dennisocana** [comment]
@phbrgnomo we discussed during today's client standup the best approach for the stories in point 3 https://github.com/CoinAlpha/hummingbot/issues/3456 and point 4 https://github.com/CoinAlpha/hummingbot/issues/3455. As mentioned by @Nullably, this change would also be required for all connectors we support. We can go with that approach but would not be efficient since we have 30 connectors. So engineering is thinking we should apply these fixes for connectors for now like Binance, KuCoin, AscendEx. Let us know your thoughts on this.

**Comment by dennisocana** [comment]
Epic https://github.com/CoinAlpha/hummingbot/issues/3470 was created to fix the issue. Closing the investigation story.
