### ISSUE TITLE
Multiple Connectors - Long delay when starting a strategy

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#3449]
**Describe the bug**
When starting a strategy, there are delays around 20 seconds up to two minutes. This randomly happens and typically occurs after restarting a strategy (stop and start).

Affected connectors:
AscendEx: #3406
Coinzoom: #3448
Crypto.com: Randomly happens, if it does, you can stop and start the strategy to jump-start and won't have a delay.
**Steps To Reproduce**
1. Create any strategy using the affected connectors and start the strategy.
2. Stop the current strategy then start again - issue typically occurs after the strategy restart base on the initial test done on our test server.

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/119682592-95496b80-be75-11eb-905e-fff5b56ada92.png)
![image](https://user-images.githubusercontent.com/57189990/119682618-9c707980-be75-11eb-8821-f987bd499dbf.png)
![image](https://user-images.githubusercontent.com/57189990/119682677-a85c3b80-be75-11eb-9f5d-c557023c9ce9.png)
![image](https://user-images.githubusercontent.com/57189990/120128920-9f60c680-c1f5-11eb-8f35-e900affd3e71.png)

**Release version**
0.39.0

**Attachments**
[logs_conf_liquidity_mining_1.log](https://github.com/CoinAlpha/hummingbot/files/6547636/logs_conf_liquidity_mining_1.log)
[logs_conf_pure_mm_2.log](https://github.com/CoinAlpha/hummingbot/files/6547637/logs_conf_pure_mm_2.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by CrimsonJacket** [comment]
**Initial investigation**
- ~~`last_recv_time` of the `UserStreamAPIDataSource` does not seem to be update after subscribing to the relevant private WebSocket channels.~~
  - This appears to be a one-off incident due to failure to subscribe
- `account_balance` does not seem to be fetched when restarting strategy. 
  - This seems to be more prevalent in connectors that does not support user balance WS channels.
  - `_update_balances()` is only called when the condition for the status poll interval is met(see `tick()`)
  
**Proposed Fix:**
- Explicitly call `_update_balance()` within `start_network()`. This will ensure that the `_update_balance()` is called every time the user issues the `start` command

**Comment by CrimsonJacket** [comment]
Looking into the the timestamps as Jack mentioned it seems to be a race condition between `tick()` and `status_polling_loop()`

Scenario 1: (Delayed start)
1. `tick()` gets called first:
- `self._poll_notifier.set()` 

2. `status_polling_loop()` gets called
- `self._poll_notifier = asyncio.Event()` <- resets the event
- `await self._poll_notifier.wait()` <- waits for event to be `.set()`

3.`tick()` gets called
- Only after the poll interval(after x mins) is reached, `.set()` is called

4. `status_polling_loop()` gets called
- proceeds to call `_update_balance()` 

Scenario 2: (regular start)
1. `status_polling_loop()` gets called first
- `self._poll_notifier = asyncio.Event()` <- resets the event
- `await self._poll_notifier.wait()` <- waits for event to be `.set()`

2. `tick()` gets called :
- `self._poll_notifier.set()` 

3. `status_polling_loop()` gets called
- proceeds to call `_update_balance()`

**Comment by dennisocana** [comment]
Fixed in version 0.40 release.
