### ISSUE TITLE
Telegram Bot Api Depricated

### ISSUE THREAD

**Issue by bmabir17** [CoinAlpha/hummingbot#3658]
**Describe the bug**
The After adding telegram config by following the [integration docs](https://docs.hummingbot.io/features/telegram/#gatsby-focus-wrapper). I am getting the following error after starting the humming bot
![Screenshot from 2021-06-30 14-57-09](https://user-images.githubusercontent.com/5344072/123932800-9b21f780-d9b3-11eb-8ea0-41ab5741e1d8.png)

Here are the steps to reproduce the issue:
Running on docker image
Only Happens when telegram_enabled is True

**Release version**
Version: 0.40.0

**Comment by sidmontanez** [comment]
Hi @bmabir17 I tried to check on my bot that as `telegram_enabled` and I don't seem to encounter the same error. I'm also running on docker v 0.40.0. I just want to confirm If you're using a Rpi to access the Hummingbot client? If so, on what version are you currently running the bot? 

If it's not too much to ask, can I have a copy of your `log` file when you encountered this issue so we could try to investigate this issue further. Thanks!

**Comment by rapcmia** [comment]
Hi @bmabir17 this is a known concern that occurred when the telegram made an [upgrade](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-12.0url). Currently the telegram integration we have is a bit of a hack so we can make use of this app to monitor the bot and the team plans to improve it on future releases. Hummingbot and telegram should still work despite getting the error on logs. For now, you can ignore it. 

We would need to close the ticket as this is expected behavior but if you have other issues with the client please send us a message on our support channel or create a bug ticket. Thanks for your time!

**Comment by mariomurrent-softwaresolutions** [comment]
Same problem here :(
