### ISSUE TITLE
Uniswap v3 strategy polling errors

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#3750]
While maintaining a position, the strategy often returns errors due to fetching balances from Gateway. If this is due to slower responses from the Uniswap API, maybe a longer timeout before the error is thrown?

<img width="1257" alt="Screen Shot 2021-07-17 at 9 13 24 PM" src="https://user-images.githubusercontent.com/1795030/126055450-4403aff5-602f-444a-b90a-adc4de79781a.png">

[logs_conf_uniswap_v3_lp_7.log](https://github.com/CoinAlpha/hummingbot/files/6835662/logs_conf_uniswap_v3_lp_7.log)

**Comment by vic-en** [comment]
I suspect this issue originates from infura provider, which could be because we do not cache data and poll for updates multiple times within same block time which result in thousands of calls within a short time.
Lastly, I'll suggest we close this issue and reopen if it persist with Gateway-v2. Since there's plan to cache in V2.
