### ISSUE TITLE
Research / Investigate Bybit Derivatives Connector

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#3752]
Look through Bybit API docs to investigate / research to define how to build the connector or if there's any missing information that we need to coordinate with their team internally ahead of time.

API docs: https://bybit-exchange.github.io/docs/inverse/#t-introduction

## Acceptance Criteria
Create tasks required to complete the connector and link to the [Bybit connector epic](https://github.com/CoinAlpha/hummingbot/issues/2509). Identify and add in the comments if there are idiosyncrasies we need to do compared to a normal exchange connector.

**Comment by aarmoa** [comment]
Considerations found during investigation:

- The server timestamp is important. If a request requires the timestamp and we are not synchronized with the server time we will not get a response. We need to keep track of the difference between server time and client time, and have a way to get the estimated server time at any moment.
- Parameters in any request should be ordered in alphabetical order. The only exception is the "sign" parameter that always goes last.
- Provides endpoint to get order book: yes
The depth is fixed (50 orders on each side)
- Fees are specified per instrument.
- Max/min prices and max/min quantities are specified per instrument.
- Provide endpoint to get trades from user: yes
- Provide endpoint to get balance: yes
- Provide websocket and subscriptions: yes
-- order book
-- trades execution
-- position

API Rate Limits
There are two levels.
For API requests there is an IP limit that applied to GET and POST requests
- Max amount of request in 2 minutes
- Max amount of request in 5 seconds
There is also a limit based on UID and per endpoint. It is based on number of requests per minute. There are groups of endpoints and each endpoint has a "value" or "cost" (not all of them consume the same amount of limit credits).

There is also a limit on number of orders (500). We need to enforce it because when it is reached the new order is created, but the older one will be automatically canceled.

**Comment by dennisocana** [comment]
Thanks @aarmoa , I also created the tasks 1-3 for building this connector and attached to its epic. Feel free to create additional stories required as discussed during the last standup.
