### ISSUE TITLE
[Bug] Discover Strategy is not working with Binance-Binance

### ISSUE THREAD

**Issue by meauxt** [CoinAlpha/hummingbot#393]
**Describe the bug**
when I am trying to run discovery and choosing 1st and 2nd exachange as binance am getting error :

**Steps To Reproduce**
start hummingbot with discover strategy and choose ur first and second exchange as binance, keep all the pairs and with any profit

...

**Logs**
  File "hummingbot/market/binance/binance_market.pyx", line 304, in hummingbot.market.binance.binance_market.BinanceMarket.split_symbol
    raise ValueError(f"Error parsing symbol {symbol}: {str(e)}")
ValueError: Error parsing symbol BNBUSDS: 'NoneType' object has no attribute 'group'

**Release version**
0.8.0
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** NFLX#2420
**Optional: your ETH address:** 0x6471ec3bf8ceff3842f1baac8911e798e64ad6bd

**Comment by vivianrc** [comment]
Hi @meauxt ! So the Discovery strategy is helping users find arbitrage opportunities between two different markets because different markets are more likely to dislocate. Theoretically, you can arbitrage the same exchange (i.e. BTC/USDT and BTC/USDC on the same exchange), but prices are less likely to dislocate and create an arbitrage opportunity. Our bot currently supports Arbitrage strategies on the same exchange, but not for Discovery yet. We plan to improve the Discovery strategy over time and may add this functionality.

**Comment by nkona** [comment]
Hey @meauxt ! What was the status of the bot when this error occurred (was it in the config stage, during initialization, after running for a while)? It would also be great if you could attach your log file so we can take a closer look at that.

**Comment by Steve1943** [comment]
This duplicates #390

**Comment by nkona** [comment]
Sounds good, we'll take a look at those. It's important to note that the discovery strategy is currently a WIP and we are planning to improve functionality and UX in future updates. In this case, however, the issue appears to be fixed in the latest dev version, so it should be correct in the next release.
