### ISSUE TITLE
Model and estimate the number of Ethereum API calls needed for AMM and Uniswap v3

### ISSUE THREAD

**Issue by martinkou** [CoinAlpha/hummingbot#4053]
## Why

See "Node API rate limits" section of https://www.notion.so/hummingbot/Robustness-and-Reliability-0d3ba2870231494a9f45d00cf732a092

One of the reasons we had the Infura rate limit issue in gateway v1 was insufficient understanding of how many API requests are needed given the current design.

We should have a good model of how the number of requests changes w/ the gateway design, and the strategies used in Hummingbot - before we can fully commit to a certain design. The model would also be useful when we need to add new features or make modifications to gateway later on.

## What

* Document a model and an estimate of Ethereum API calls needed for running Uniswap AMM and Uniswap V3 strategies, under reasonably expected and heavy use case scenarios.

**Comment by vic-en** [comment]
**Uniswap v2:**
![Screenshot 2021-09-28 at 19-49-46 Ethereum API IPFS API Gateway ETH Nodes as a Service Infura](https://user-images.githubusercontent.com/31972210/135361763-c54caf07-305e-4e56-b981-e56d2b17a641.png)
![uv2](https://user-images.githubusercontent.com/31972210/135361861-88cd03ae-fe9b-486b-9513-c6afbf8b2b6b.png)
Note: Executing an arbitrage leg can significantly increase the number of calls due to polling as often as the status_polling loop runs.
Also, the reason why the estimated values differs from the estimated values is due to the fact that each polling loops on the client do not run in parallel.i.e. they use while loops which makes them not to execute another interation at the next interval which happens if the https calls do not return on time.

At that rate we can expect that instance to make ~20k calls in a day, not including the extra calls that are made when abitrages occur which can double or even tripple that value.

**Uniswap v3:**
![Screenshot 2021-09-30 at 00-19-52 Ethereum API IPFS API Gateway ETH Nodes as a Service Infura](https://user-images.githubusercontent.com/31972210/135361925-955765e3-85ad-4263-82c4-343cae205bdb.png)
Uniswap v3 on the other hand makes alot of calls. Knowing the exact number of calls to Infura per request from the client is tricky due to the fact that most of those calls are made by the uniswap v3 sdk.
~304k of calls will be made in total for a period of 24 hour which will be above the limit allowed by Infura.

**Comment by vic-en** [comment]
From further investigating the Uniswap v3 connector and strategy, the estimated calls per request is as follows:2
![univ3](https://user-images.githubusercontent.com/31972210/135856948-21701882-83da-48f6-85c6-5eef56d00ca1.png)
**Note:** Number of call to poll for status of transactions and approval isn't included as those can vary depending on gas price and network condition.

**Comment by mifeng** [comment]
Done. Next steps: implement caching and change logic to reduce unneeded calls
