### ISSUE TITLE
decimal.InvalidOperation error when running spot perpetual strategy

### ISSUE THREAD

**Issue by scrollinondubs** [CoinAlpha/hummingbot#4103]
**Describe the bug**
Upon starting the spot perpetual strategy it repeatedly throws the error: **decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]**

**Steps To Reproduce**
create a new spot perpetual strategy (I used binance as spot and binance perpetual testnet as derivative)
Start the strategy using the start command
You will get the following in the error log: 
```
  File "/home/hummingbot/hummingbot/strategy/spot_perpetual_arbitrage/spot_perpetual_arbitrage.py", line 160, in main
    await self.current_proposal.proposed_spot_deriv_arb()
  File "/home/hummingbot/hummingbot/strategy/spot_perpetual_arbitrage/arb_proposal.py", line 90, in proposed_spot_deriv_arb
    if (sum(self.spot_buy_sell_prices) / 2) > (sum(self.deriv_buy_sell_prices) / 2):  # Backwardation
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
2021-09-07 14:26:33,002 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: [<class 'decimal.InvalidOperation'>]
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c 
``` 
...

**Screenshots**
https://www.loom.com/share/8047a44217414db291fba9b9e5854831

**Release version**
0.42

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[spot-perpetual-conf-file.txt](https://github.com/CoinAlpha/hummingbot/files/7122586/spot-perpetual-conf-file.txt)
[spot-perpetual-log.txt](https://github.com/CoinAlpha/hummingbot/files/7122587/spot-perpetual-log.txt)
<img width="640" alt="Screen Shot 2021-09-07 at 3 52 04 PM" src="https://user-images.githubusercontent.com/633110/132369648-c478ea17-4b27-40df-9ac8-cc6e76cbde0b.png">

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by Jurelll** [comment]
Hi @scrollinondubs 

I can see here you are still using the 0.42 version, may we suggest getting the 0.43 version and see if the error still persist. Just in case you're still getting the same error can you try and change your `rate_oracle_source` to coingecko. If you're going to change it to Ascendex or Kucoin, it does not support USD. You will need to change your `global_token` to USDT.

For further questions you may proceed and chat with us here:
https://support.hummingbot.io/hc/en-us

Regards,
Jurell
Hummingbot Support Team

**Comment by scrollinondubs** [comment]
@Jurelll I tried following the instructions [here](https://docs.hummingbot.io/installation/update-hummingbot/) to update the instance to 0.43 but it still shows it's running 0.42. I'm using Docker. Is 0.43 a different tag other than latest such that I need to modify the update script?  Not sure why it's still on 0.42 after following those instructions... 

I switched the rate_oracle_source setting to Coingecko per your instructions but it's still throwing that same error. I will mess with it and see if I can figure out another way to update the instance to 0.43. Any tips appreciated.

**Comment by scrollinondubs** [comment]
Update on this: I wasn't ever able to update the existing instance but I was able to create a new one  using the tag "version-0.43.0" and then copy my "hummingbot_files" directory over and get an updated instance running that way. 

Unfortunately that same error persists for me. Any recommendations?

**Comment by viktorya777** [comment]
Hello @scrollinondubs!
I have just tested it on my end.
I was getting the same error with RUNE-USDT pair.
But when I changed the trading pair there was no error.
The issue occurred because there is not enough orders on the order book for RUNE-USDT in Binance Perpetual Testnet.  I would suggest you to use other pairs for Binance Perpetual Testnet that have both buy and sell orders. 
Keep us updated!

Regards,
Viktorya
Hummingbot Support Team

**Comment by gerald-hb** [comment]
Here's a summary of my test results
Binance Perpetual (live) - XEM-USDT = Ok
![image](https://user-images.githubusercontent.com/84826167/132628231-bc177ec0-9a0e-4475-b052-a28f33e660f8.png)
Binance Perpetual (live) - RUNE-USDT = Ok
![image](https://user-images.githubusercontent.com/84826167/132628560-ba10e6d1-0ff4-43ca-90aa-a06ceca200f1.png)
Binance Perpetual Testnet - XEM-USDT = Ok
![image](https://user-images.githubusercontent.com/84826167/132628617-169bbac9-291c-4988-97c1-2c34526eaaae.png)
Binance Perpetual Testnet = RUNE-USDT - Immediately get the reported decimal error. As Viktorya mentioned, it could be due to the empty orderbook in binance testnet
![image](https://user-images.githubusercontent.com/84826167/132629582-4a0c2093-bcfe-46ca-a818-cd575b6192dd.png)
Orderbook for RUNE-USDT in testnet
![image](https://user-images.githubusercontent.com/84826167/132629756-3989c003-eca8-4c2b-94f5-a656cd113ab4.png)

**Comment by scrollinondubs** [comment]
@viktorya777 @gerald-hb sorry for the delay - just now seeing your messages. Confirmed that when I switch trading pairs to LTC-USDT the error goes away. Sorry for the false alarm on this. Lesson learned to check the testnet market order book depth before assuming there's liquidity.
