### ISSUE TITLE
Show inside Hummingbot Client which connector is Core or Community

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#4495]
┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0d3b) by [Unito](https://www.unito.io)

**Comment by mifeng** [comment]
I would assess whether this feature is really helpful for users, because it would increase the maintenance load by requiring changes to the client code to match the documentation. Since we want the community to handle as much as the work as possible, I think it would be better if only the docs contained information about the connector and the client just provided a link to the docs.
