### ISSUE TITLE
Gate_io: High memory usage

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#4683]
**Describe the bug**
Opening ticket for tracking: We have observe a high memory usage on our gate_io test bot while testing a pull request. In the UI, the memory stays within 200+MB however when we check the memory usage using HTOP, it increases over time. The highest so far that we've seen reached up to 3+GB. This behaviour persist as well in the development branch.

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create an Avellaneda MM, Liquidity mining, or pure market making strategy using Gate_io
2. Use ETH_USDT as market
3. Start the strategy and leave it running for long period.
4. Monitor the memory usage from time to time using top or htop
...

**Screenshots**
After running the bot for about 24 hours or more:
![image](https://user-images.githubusercontent.com/57189990/141034397-8a20d12b-327e-4744-9b73-5adef914974a.png)

After running the bot for 6 hours:
![image](https://user-images.githubusercontent.com/57189990/141034952-963bcc17-763e-455a-9060-fcfdb6912096.png)

**Release version**
0.45.0

**Attachments**

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by dennisocana** [comment]
Tagging as a P1 issue since we just launched Gate.io liquidity mining beta. When we start launching more campaigns, users will create more instances in parallel and would more likely run into this problem when using the bot.

**Comment by SickProdigy** [comment]
I think it is also an issue on binance_us. Was having an issue with my small vm had to upgrade the vm because a program was hanging. Just now realizing it was this. Looking at my stats it hovered around 200 and slowly increased to 300mb before i noticed. I was testing some other scripts so i figured it was that. 

I was looking for some answers about gate_io but I see it is a bit newer now. Put some money in gate_io and tried to test and wouldn't let me. Anyway to bypass that I may have overlooked?

**Comment by cali-tomas** [comment]
Hi, can you send a screenshot after connceting to gate_io. Also is your API key v4?

**Comment by SickProdigy** [comment]
> 
> 
> Hi, can you send a screenshot after connceting to gate_io. Also is your API key v4?

I was using v1/2 to my mistake and switched to v4. Working fine now.

I have 3 instances running together that seem to be using about 1 gb of ram. They are also dockerized. Not sure if I've had a spike since friday. 4gb server seems to be keeping up atleast. Dont think 1/2 gb can run 1 instance in a vm.
