### ISSUE TITLE
Error in Bot: Cannot submit buy or sell order in Azure cloud, Getting error as cannot fetch server update

### ISSUE THREAD

**Issue by vibhorkumar31** [CoinAlpha/hummingbot#624]
I have a problem with the bot, because I cant submit any buy or sell order. I always run into an error. I run two bots at the same time on the Azure Cloud, but I always get the Warning that I cannot fetch a server update.

I have attached the screenshot of error message and logs 

User: OZ

<img width="1265" alt="Azurebot" src="https://user-images.githubusercontent.com/43172693/62605016-dc6c1280-b916-11e9-905a-c1e5d081028c.png">
[hummingbot_log.txt](https://github.com/CoinAlpha/hummingbot/files/3475848/hummingbot_log.txt)

**Comment by rennel-tabing** [comment]
rennel | support: @0z Have you checked if you somehow hit your Ethereum node limit? For example, the Infura's  free node have a limit of 100,000 requests per day.
 
0z: @rennel | support  just checked it, I am  at around 80.000
 
rennel | support: 
@0z based on the logs you have provided, I see a possible network connection and too many request attempt. Please try to stop and start a hummingbot so that it will reinitializes the connection. Let us  know if that made a difference.

0z: 
I tried that already before, it happens all the time. I haven't made a single trade with the bot and i cant find the solution. do you think it could be an issue with radar relay? should i try another dex?

rennel | support: 
its possible. Please see this error from the logs
Error fetching data from https://api.radarrelay.com/v2/orders/0x6b423f7c1e9f8cbe94688ceba2dbaabdf10c96b3bcc0c724f5d1c76f6f09a85a. HTTP status is 429 - Too many requests, please try again later.
as the URL points to radarrelay

0z: hmm ok I'll try with another dex
thanks

**Comment by rennel-tabing** [comment]
[https://cdn.discordapp.com/attachments/563462222878212098/608558955542872064/conf_cross_exchange_market_making_strategy_1.yml](url)

[https://cdn.discordapp.com/attachments/563462222878212098/608559181531840516/Azurebot.png](url)

**Comment by carlolm** [comment]
@rennel-tabing that message suggests that it's a rate limiting error with Radar Relay rather than with the infura node.  

@chowryan limit order expiration is 130s in configs.  So if hitting rate limits on radar, it may be some other functions being called that are triggering rate limits.

![image](https://user-images.githubusercontent.com/12274903/62642710-2d6e0d80-b8fb-11e9-9b39-157998d7182a.png)

**Comment by carlolm** [comment]
Search for rate limit here: https://developers.radarrelay.com/

**Comment by chowryan** [comment]
try running 1 bot per IP. All exchange interactions are optimized for 1 instance only.
