### ISSUE TITLE
[BUG] XEMM: Sending duplicate orders after stopped

### ISSUE THREAD

**Issue by joesixpack** [CoinAlpha/hummingbot#720]
**Describe the bug**
Running the XEMM between two stablecoin pairs on Binance, after stopping the bot, the network spontaneously reconnected and sent two identical maker orders on the same side!  Had to cancel them all at Binance three times in a row before I exited Hummingbot to stop it.

**Steps To Reproduce**
Load Hummingbot, import xemm config, start, stop.

**Release version**
Version: 0.13.0

**Attachments**
[xemmbug.zip](https://github.com/CoinAlpha/hummingbot/files/3561986/xemmbug.zip)

Your ETH address: Provided upon request.

**Comment by rennel-tabing** [comment]
I am able to reproduce this bug. After stopping the bot you will see a message "All outstanding orders has been cancelled" but checking on the actual binance account shows that the order is still placed.

**Comment by chowryan** [comment]
@rennel-tabing we need your configs and screenshot

**Comment by rennel-tabing** [comment]
I re-run the strategy today to get a screenshot but I am no longer getting the issue on my end. The config was on the attachment the user have provided.
@joesixpack Can you confirm if you can still observe the same behavior when running the bot on your end?

**Comment by joesixpack** [comment]
Don't see it atm.  Is it possible stacking multiple starts caused it?

**Comment by rennel-tabing** [comment]
The issue I encountered is similar to the test I did last August 31st

After exiting the bot, it says that the order has been cancelled
![image](https://user-images.githubusercontent.com/53868268/69241580-17fcb680-0b6d-11ea-905f-b1c985e57c9e.png)

Looking on the actual binance account shows that the orders are still outstanding
![image](https://user-images.githubusercontent.com/53868268/69241686-3ebaed00-0b6d-11ea-9055-0712c722fde6.png)

Here is my `list configs` command output
![image](https://user-images.githubusercontent.com/53868268/69241889-b8eb7180-0b6d-11ea-8723-1a2864e85b56.png)

You will also notice that it posted/ordered a taker symbol of `ONE/USDC` instead of a `ONE/USDT` on binance.

**Comment by mifeng** [comment]
#1683 may have fixed this issue too.
