### ISSUE TITLE
[Feature]Automatic Deleting of Out-Dated Log Files 

### ISSUE THREAD

**Issue by BUDDHA-TONY** [CoinAlpha/hummingbot#897]
A code that if enabled will delete out-dated  (30Day's) log files or before it reaches the maximum capacity of the disk memory, before it delete will prompt y/n to approve the execution of code or will prompt transfer files to external hard drive then prompt y/n.

I think this would be a good new feature for humming-bot .As user have previous problems with different sizes of logs, filling there disk space.

**Comment by PtrckM** [comment]
here is a simple linux command you can try:

`find . -type f -name '*.log' -mtime +30 -delete`

- it will use the `find` command on linux and search the current location for all files with a extension name **log** and look for files with older than 30 days and deletes them

Note: Using this command will not undo the deleted files.

Tip: You can use cron job to automate this :)

**Comment by mifeng** [comment]
Thanks for the feature suggestion. I agree that the way that Hummingbot handles log files is a bit sub-optimal right now, since they can balloon to quite a large size after a while.

@PtrckM's suggestion is a good stopgap, but we should also alleviate this issue with a proper fix within the next few months.

**Comment by yzhang1994** [comment]
We have added log-rotation to the 0.17.0 release. Hope it helps.
